//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取设置.
        /// </summary>
        public static string DrawSettings {
            get {
                return ResourceManager.GetString("DrawSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        public static string ExitProgram {
            get {
                return ResourceManager.GetString("ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸抽取.
        /// </summary>
        public static string FaceDraw {
            get {
                return ResourceManager.GetString("FaceDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗管理.
        /// </summary>
        public static string FloatingWindowManagement {
            get {
                return ResourceManager.GetString("FloatingWindowManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联动设置.
        /// </summary>
        public static string LinkageSettings {
            get {
                return ResourceManager.GetString("LinkageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖.
        /// </summary>
        public static string Lottery {
            get {
                return ResourceManager.GetString("Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知设置.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知设置.
        /// </summary>
        public static string RollCallNotificationSettings {
            get {
                return ResourceManager.GetString("RollCallNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知设置.
        /// </summary>
        public static string QuickDrawNotificationSettings {
            get {
                return ResourceManager.GetString("QuickDrawNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知设置.
        /// </summary>
        public static string LotteryNotificationSettings {
            get {
                return ResourceManager.GetString("LotteryNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主窗口.
        /// </summary>
        public static string OpenMainWindow {
            get {
                return ResourceManager.GetString("OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开设置.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽.
        /// </summary>
        public static string QuickDraw {
            get {
                return ResourceManager.GetString("QuickDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名.
        /// </summary>
        public static string RollCall {
            get {
                return ResourceManager.GetString("RollCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名单管理.
        /// </summary>
        public static string RosterManagement {
            get {
                return ResourceManager.GetString("RosterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        public static string SecuritySettings {
            get {
                return ResourceManager.GetString("SecuritySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string ThemeManagement {
            get {
                return ResourceManager.GetString("ThemeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计时器.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新设置.
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语音设置.
        /// </summary>
        public static string VoiceSettings {
            get {
                return ResourceManager.GetString("VoiceSettings", resourceCulture);
            }
        }
    }
}
