//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementSubPages.TablePreview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagementSubPages.TablePreview.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string ColumnEnabled {
            get {
                return ResourceManager.GetString("ColumnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string ColumnGender {
            get {
                return ResourceManager.GetString("ColumnGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组.
        /// </summary>
        public static string ColumnGroup {
            get {
                return ResourceManager.GetString("ColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品.
        /// </summary>
        public static string ColumnPrize {
            get {
                return ResourceManager.GetString("ColumnPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string ColumnSerial {
            get {
                return ResourceManager.GetString("ColumnSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string ColumnStudentId {
            get {
                return ResourceManager.GetString("ColumnStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string ColumnTags {
            get {
                return ResourceManager.GetString("ColumnTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string ColumnWeight {
            get {
                return ResourceManager.GetString("ColumnWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览当前奖池的奖品名单表格。.
        /// </summary>
        public static string LotteryTableDesc {
            get {
                return ResourceManager.GetString("LotteryTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖表格.
        /// </summary>
        public static string LotteryTableTitle {
            get {
                return ResourceManager.GetString("LotteryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择班级.
        /// </summary>
        public static string PleaseSelectClass {
            get {
                return ResourceManager.GetString("PleaseSelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择奖池.
        /// </summary>
        public static string PleaseSelectPool {
            get {
                return ResourceManager.GetString("PleaseSelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览当前班级的学生名单表格。.
        /// </summary>
        public static string RollCallTableDesc {
            get {
                return ResourceManager.GetString("RollCallTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名表格.
        /// </summary>
        public static string RollCallTableTitle {
            get {
                return ResourceManager.GetString("RollCallTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择班级.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 个奖品.
        /// </summary>
        public static string TotalPrizes {
            get {
                return ResourceManager.GetString("TotalPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共 {0} 名学生.
        /// </summary>
        public static string TotalStudents {
            get {
                return ResourceManager.GetString("TotalStudents", resourceCulture);
            }
        }
    }
}
