//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.LinkageSettingsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.LinkageSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上节课.
        /// </summary>
        public static string BreakAssignmentClass {
            get {
                return ResourceManager.GetString("BreakAssignmentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下节课.
        /// </summary>
        public static string BreakAssignmentDay {
            get {
                return ResourceManager.GetString("BreakAssignmentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间.
        /// </summary>
        public static string BreakAssignmentOff {
            get {
                return ResourceManager.GetString("BreakAssignmentOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间禁用设置.
        /// </summary>
        public static string ClassBreak {
            get {
                return ResourceManager.GetString("ClassBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除课表.
        /// </summary>
        public static string ClearCsesSchedule {
            get {
                return ResourceManager.GetString("ClearCsesSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSES课程表导入.
        /// </summary>
        public static string CsesImport {
            get {
                return ResourceManager.GetString("CsesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据源选择.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据源选择.
        /// </summary>
        public static string DataSourceMode {
            get {
                return ResourceManager.GetString("DataSourceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用ClassIsland数据源.
        /// </summary>
        public static string DataSourceModeClassIsland {
            get {
                return ResourceManager.GetString("DataSourceModeClassIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用CSES课表数据.
        /// </summary>
        public static string DataSourceModeCses {
            get {
                return ResourceManager.GetString("DataSourceModeCses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择课程数据的来源.
        /// </summary>
        public static string DataSourceModeDesc {
            get {
                return ResourceManager.GetString("DataSourceModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不使用数据源.
        /// </summary>
        public static string DataSourceModeManual {
            get {
                return ResourceManager.GetString("DataSourceModeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间禁用功能.
        /// </summary>
        public static string EnableClassBreak {
            get {
                return ResourceManager.GetString("EnableClassBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启后，在下课时间段内抽取需要安全验证.
        /// </summary>
        public static string EnableClassBreakDesc {
            get {
                return ResourceManager.GetString("EnableClassBreakDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前重置功能.
        /// </summary>
        public static string EnablePreClassReset {
            get {
                return ResourceManager.GetString("EnablePreClassReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后，在上课前指定秒数内自动清除临时记录和界面结果.
        /// </summary>
        public static string EnablePreClassResetDesc {
            get {
                return ResourceManager.GetString("EnablePreClassResetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目历史记录过滤.
        /// </summary>
        public static string EnableSubjectHistoryFilter {
            get {
                return ResourceManager.GetString("EnableSubjectHistoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后，计算权重时只使用当前科目的历史记录.
        /// </summary>
        public static string EnableSubjectHistoryFilterDesc {
            get {
                return ResourceManager.GetString("EnableSubjectHistoryFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证流程功能.
        /// </summary>
        public static string EnableVerificationFlow {
            get {
                return ResourceManager.GetString("EnableVerificationFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后，在非上课时段触发时将弹出安全验证；若关闭则直接禁用控件.
        /// </summary>
        public static string EnableVerificationFlowDesc {
            get {
                return ResourceManager.GetString("EnableVerificationFlowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能正在开发中.
        /// </summary>
        public static string FeatureInDevelopment {
            get {
                return ResourceManager.GetString("FeatureInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗.
        /// </summary>
        public static string FloatingWindow {
            get {
                return ResourceManager.GetString("FloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下课时隐藏悬浮窗.
        /// </summary>
        public static string HideFloatingWindowOnClassEnd {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnClassEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当检测到下课（非上课时段）时自动隐藏浮窗.
        /// </summary>
        public static string HideFloatingWindowOnClassEndDesc {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnClassEndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从剪贴板导入.
        /// </summary>
        public static string ImportFromCsesClipboard {
            get {
                return ResourceManager.GetString("ImportFromCsesClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从剪贴板读取 CSES JSON 并导入.
        /// </summary>
        public static string ImportFromCsesClipboardDesc {
            get {
                return ResourceManager.GetString("ImportFromCsesClipboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入.
        /// </summary>
        public static string ImportFromCsesFile {
            get {
                return ResourceManager.GetString("ImportFromCsesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 CSES 导出的 JSON 文件并导入.
        /// </summary>
        public static string ImportFromCsesFileDesc {
            get {
                return ResourceManager.GetString("ImportFromCsesFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未导入课程表.
        /// </summary>
        public static string NoScheduleImported {
            get {
                return ResourceManager.GetString("NoScheduleImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看当前配置.
        /// </summary>
        public static string OpenCurrentCsesConfig {
            get {
                return ResourceManager.GetString("OpenCurrentCsesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看当前已导入的 CSES 配置.
        /// </summary>
        public static string OpenCurrentCsesConfigDesc {
            get {
                return ResourceManager.GetString("OpenCurrentCsesConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下课后延迟禁用时间.
        /// </summary>
        public static string PostClassDisableDelay {
            get {
                return ResourceManager.GetString("PostClassDisableDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下课后多少秒内延迟触发课间禁用（0-1440秒）.
        /// </summary>
        public static string PostClassDisableDelayDesc {
            get {
                return ResourceManager.GetString("PostClassDisableDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上课前提前解禁时间.
        /// </summary>
        public static string PreClassEnableTime {
            get {
                return ResourceManager.GetString("PreClassEnableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在上课前多少秒提前解禁（0-1440秒）.
        /// </summary>
        public static string PreClassEnableTimeDesc {
            get {
                return ResourceManager.GetString("PreClassEnableTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前重置设置.
        /// </summary>
        public static string PreClassReset {
            get {
                return ResourceManager.GetString("PreClassReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课前重置时间.
        /// </summary>
        public static string PreClassResetTime {
            get {
                return ResourceManager.GetString("PreClassResetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在上课前多少秒清除临时记录和界面结果（1-1440秒）.
        /// </summary>
        public static string PreClassResetTimeDesc {
            get {
                return ResourceManager.GetString("PreClassResetTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程表导入.
        /// </summary>
        public static string ScheduleImport {
            get {
                return ResourceManager.GetString("ScheduleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从CSES格式文件导入上课时间段，用于课间禁用功能.
        /// </summary>
        public static string ScheduleImportDesc {
            get {
                return ResourceManager.GetString("ScheduleImportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目历史记录过滤.
        /// </summary>
        public static string SubjectHistory {
            get {
                return ResourceManager.GetString("SubjectHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间归属.
        /// </summary>
        public static string SubjectHistoryBreakAssignment {
            get {
                return ResourceManager.GetString("SubjectHistoryBreakAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课间时段的科目历史记录归属到哪一类.
        /// </summary>
        public static string SubjectHistoryBreakAssignmentDesc {
            get {
                return ResourceManager.GetString("SubjectHistoryBreakAssignmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证流程.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
    }
}
