//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.FloatingWindowPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.FloatingWindowPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观设置.
        /// </summary>
        public static string AppearanceSettings {
            get {
                return ResourceManager.GetString("AppearanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅图标.
        /// </summary>
        public static string DisplayStyleIcon {
            get {
                return ResourceManager.GetString("DisplayStyleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图标+文字.
        /// </summary>
        public static string DisplayStyleIconText {
            get {
                return ResourceManager.GetString("DisplayStyleIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅文字.
        /// </summary>
        public static string DisplayStyleText {
            get {
                return ResourceManager.GetString("DisplayStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不抢占焦点.
        /// </summary>
        public static string DoNotStealFocus {
            get {
                return ResourceManager.GetString("DoNotStealFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击悬浮窗时尽量不切换焦点.
        /// </summary>
        public static string DoNotStealFocusDesc {
            get {
                return ResourceManager.GetString("DoNotStealFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 箭头.
        /// </summary>
        public static string EdgeDisplayStyleArrow {
            get {
                return ResourceManager.GetString("EdgeDisplayStyleArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图标.
        /// </summary>
        public static string EdgeDisplayStyleIcon {
            get {
                return ResourceManager.GetString("EdgeDisplayStyleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字.
        /// </summary>
        public static string EdgeDisplayStyleText {
            get {
                return ResourceManager.GetString("EdgeDisplayStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴边设置.
        /// </summary>
        public static string EdgeSettings {
            get {
                return ResourceManager.GetString("EdgeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展快速抽取组件.
        /// </summary>
        public static string ExtendQuickDrawComponent {
            get {
                return ResourceManager.GetString("ExtendQuickDrawComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在悬浮窗中显示更多快速抽取信息.
        /// </summary>
        public static string ExtendQuickDrawComponentDesc {
            get {
                return ResourceManager.GetString("ExtendQuickDrawComponentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸抽取.
        /// </summary>
        public static string FaceDrawButton {
            get {
                return ResourceManager.GetString("FaceDrawButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮显示.
        /// </summary>
        public static string FloatingWindowButtonControl {
            get {
                return ResourceManager.GetString("FloatingWindowButtonControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择在悬浮窗中显示的功能按钮.
        /// </summary>
        public static string FloatingWindowButtonControlDesc {
            get {
                return ResourceManager.GetString("FloatingWindowButtonControlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示样式.
        /// </summary>
        public static string FloatingWindowDisplayStyle {
            get {
                return ResourceManager.GetString("FloatingWindowDisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置按钮的展示方式.
        /// </summary>
        public static string FloatingWindowDisplayStyleDesc {
            get {
                return ResourceManager.GetString("FloatingWindowDisplayStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许拖动.
        /// </summary>
        public static string FloatingWindowDraggable {
            get {
                return ResourceManager.GetString("FloatingWindowDraggable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许拖动移动悬浮窗.
        /// </summary>
        public static string FloatingWindowDraggableDesc {
            get {
                return ResourceManager.GetString("FloatingWindowDraggableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长按触发时长.
        /// </summary>
        public static string FloatingWindowLongPressDuration {
            get {
                return ResourceManager.GetString("FloatingWindowLongPressDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拖动前需要长按的时长（毫秒）.
        /// </summary>
        public static string FloatingWindowLongPressDurationDesc {
            get {
                return ResourceManager.GetString("FloatingWindowLongPressDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 悬浮窗透明度.
        /// </summary>
        public static string FloatingWindowOpacity {
            get {
                return ResourceManager.GetString("FloatingWindowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗的不透明度（0~100）.
        /// </summary>
        public static string FloatingWindowOpacityDesc {
            get {
                return ResourceManager.GetString("FloatingWindowOpacityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 布局模式.
        /// </summary>
        public static string FloatingWindowPlacement {
            get {
                return ResourceManager.GetString("FloatingWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗的布局方向.
        /// </summary>
        public static string FloatingWindowPlacementDesc {
            get {
                return ResourceManager.GetString("FloatingWindowPlacementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸.
        /// </summary>
        public static string FloatingWindowSize {
            get {
                return ResourceManager.GetString("FloatingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗整体尺寸.
        /// </summary>
        public static string FloatingWindowSizeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动贴边.
        /// </summary>
        public static string FloatingWindowStickToEdge {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止操作后自动贴到屏幕边缘.
        /// </summary>
        public static string FloatingWindowStickToEdgeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdgeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴边显示样式.
        /// </summary>
        public static string FloatingWindowStickToEdgeDisplayStyle {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdgeDisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴边状态下的显示方式.
        /// </summary>
        public static string FloatingWindowStickToEdgeDisplayStyleDesc {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdgeDisplayStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴边恢复延迟.
        /// </summary>
        public static string FloatingWindowStickToEdgeRecoverSeconds {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdgeRecoverSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴边后恢复显示的延迟（秒）.
        /// </summary>
        public static string FloatingWindowStickToEdgeRecoverSecondsDesc {
            get {
                return ResourceManager.GetString("FloatingWindowStickToEdgeRecoverSecondsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string FloatingWindowTheme {
            get {
                return ResourceManager.GetString("FloatingWindowTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗的主题模式.
        /// </summary>
        public static string FloatingWindowThemeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶模式.
        /// </summary>
        public static string FloatingWindowTopmostMode {
            get {
                return ResourceManager.GetString("FloatingWindowTopmostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置悬浮窗的置顶方式.
        /// </summary>
        public static string FloatingWindowTopmostModeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowTopmostModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台隐藏.
        /// </summary>
        public static string ForegroundHidingSettings {
            get {
                return ResourceManager.GetString("ForegroundHidingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前台窗口时隐藏.
        /// </summary>
        public static string HideFloatingWindowOnForeground {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当特定窗口位于前台时自动隐藏悬浮窗.
        /// </summary>
        public static string HideFloatingWindowOnForegroundDesc {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForegroundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进程名包含.
        /// </summary>
        public static string HideFloatingWindowOnForegroundProcessNames {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForegroundProcessNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用英文逗号分隔，匹配进程名关键字.
        /// </summary>
        public static string HideFloatingWindowOnForegroundProcessNamesDesc {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForegroundProcessNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口标题包含.
        /// </summary>
        public static string HideFloatingWindowOnForegroundWindowTitles {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForegroundWindowTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用英文逗号分隔，匹配标题关键字.
        /// </summary>
        public static string HideFloatingWindowOnForegroundWindowTitlesDesc {
            get {
                return ResourceManager.GetString("HideFloatingWindowOnForegroundWindowTitlesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖.
        /// </summary>
        public static string LotteryButton {
            get {
                return ResourceManager.GetString("LotteryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 横向.
        /// </summary>
        public static string PlacementLandscape {
            get {
                return ResourceManager.GetString("PlacementLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 竖向.
        /// </summary>
        public static string PlacementPortrait {
            get {
                return ResourceManager.GetString("PlacementPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩形.
        /// </summary>
        public static string PlacementRectangle {
            get {
                return ResourceManager.GetString("PlacementRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽.
        /// </summary>
        public static string QuickDrawButton {
            get {
                return ResourceManager.GetString("QuickDrawButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置悬浮窗位置.
        /// </summary>
        public static string ResetFloatingWindowPosition {
            get {
                return ResourceManager.GetString("ResetFloatingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        public static string ResetFloatingWindowPositionButton {
            get {
                return ResourceManager.GetString("ResetFloatingWindowPositionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将悬浮窗位置重置为默认值.
        /// </summary>
        public static string ResetFloatingWindowPositionDesc {
            get {
                return ResourceManager.GetString("ResetFloatingWindowPositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名.
        /// </summary>
        public static string RollCallButton {
            get {
                return ResourceManager.GetString("RollCallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时显示悬浮窗.
        /// </summary>
        public static string ShowFloatingWindowOnStartup {
            get {
                return ResourceManager.GetString("ShowFloatingWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件启动后自动显示悬浮窗.
        /// </summary>
        public static string ShowFloatingWindowOnStartupDesc {
            get {
                return ResourceManager.GetString("ShowFloatingWindowOnStartupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超超大.
        /// </summary>
        public static string SizeExtraExtraLarge {
            get {
                return ResourceManager.GetString("SizeExtraExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超超小.
        /// </summary>
        public static string SizeExtraExtraSmall {
            get {
                return ResourceManager.GetString("SizeExtraExtraSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超大.
        /// </summary>
        public static string SizeExtraLarge {
            get {
                return ResourceManager.GetString("SizeExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string SizeLarge {
            get {
                return ResourceManager.GetString("SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        public static string SizeMedium {
            get {
                return ResourceManager.GetString("SizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string SizeSmall {
            get {
                return ResourceManager.GetString("SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超小.
        /// </summary>
        public static string SizeVerySmall {
            get {
                return ResourceManager.GetString("SizeVerySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随全局.
        /// </summary>
        public static string ThemeFollowGlobal {
            get {
                return ResourceManager.GetString("ThemeFollowGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string ThemeFollowSystem {
            get {
                return ResourceManager.GetString("ThemeFollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计时器.
        /// </summary>
        public static string TimerButton {
            get {
                return ResourceManager.GetString("TimerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不置顶.
        /// </summary>
        public static string TopmostModeOff {
            get {
                return ResourceManager.GetString("TopmostModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string TopmostModeOn {
            get {
                return ResourceManager.GetString("TopmostModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIA置顶.
        /// </summary>
        public static string TopmostModeUia {
            get {
                return ResourceManager.GetString("TopmostModeUia", resourceCulture);
            }
        }
    }
}
