//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementPage {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagementPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ListManagement {
            get {
                return ResourceManager.GetString("ListManagement", resourceCulture);
            }
        }

        public static string RollCallListSettings {
            get {
                return ResourceManager.GetString("RollCallListSettings", resourceCulture);
            }
        }

        public static string LotteryListSettings {
            get {
                return ResourceManager.GetString("LotteryListSettings", resourceCulture);
            }
        }
        
        public static string ListManagementNavHint {
            get {
                return ResourceManager.GetString("ListManagementNavHint", resourceCulture);
            }
        }

        public static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }

        public static string ClassManagementDesc {
            get {
                return ResourceManager.GetString("ClassManagementDesc", resourceCulture);
            }
        }

        public static string PoolManagement {
            get {
                return ResourceManager.GetString("PoolManagement", resourceCulture);
            }
        }

        public static string PoolManagementDesc {
            get {
                return ResourceManager.GetString("PoolManagementDesc", resourceCulture);
            }
        }

        public static string SetClassName {
            get {
                return ResourceManager.GetString("SetClassName", resourceCulture);
            }
        }

        public static string SetClassNameDesc {
            get {
                return ResourceManager.GetString("SetClassNameDesc", resourceCulture);
            }
        }

        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }

        public static string SelectClassDesc {
            get {
                return ResourceManager.GetString("SelectClassDesc", resourceCulture);
            }
        }

        public static string ImportStudentList {
            get {
                return ResourceManager.GetString("ImportStudentList", resourceCulture);
            }
        }

        public static string ImportStudentListDesc {
            get {
                return ResourceManager.GetString("ImportStudentListDesc", resourceCulture);
            }
        }

        public static string NameSettings {
            get {
                return ResourceManager.GetString("NameSettings", resourceCulture);
            }
        }

        public static string NameSettingsDesc {
            get {
                return ResourceManager.GetString("NameSettingsDesc", resourceCulture);
            }
        }

        public static string GenderSettings {
            get {
                return ResourceManager.GetString("GenderSettings", resourceCulture);
            }
        }

        public static string GenderSettingsDesc {
            get {
                return ResourceManager.GetString("GenderSettingsDesc", resourceCulture);
            }
        }

        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }

        public static string GroupSettingsDesc {
            get {
                return ResourceManager.GetString("GroupSettingsDesc", resourceCulture);
            }
        }

        public static string TagSettings {
            get {
                return ResourceManager.GetString("TagSettings", resourceCulture);
            }
        }

        public static string TagSettingsDesc {
            get {
                return ResourceManager.GetString("TagSettingsDesc", resourceCulture);
            }
        }

        public static string ExportStudentList {
            get {
                return ResourceManager.GetString("ExportStudentList", resourceCulture);
            }
        }

        public static string ExportStudentListDesc {
            get {
                return ResourceManager.GetString("ExportStudentListDesc", resourceCulture);
            }
        }

        public static string SetPoolName {
            get {
                return ResourceManager.GetString("SetPoolName", resourceCulture);
            }
        }

        public static string SetPoolNameDesc {
            get {
                return ResourceManager.GetString("SetPoolNameDesc", resourceCulture);
            }
        }

        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }

        public static string SelectPoolDesc {
            get {
                return ResourceManager.GetString("SelectPoolDesc", resourceCulture);
            }
        }

        public static string ImportPrizeList {
            get {
                return ResourceManager.GetString("ImportPrizeList", resourceCulture);
            }
        }

        public static string ImportPrizeListDesc {
            get {
                return ResourceManager.GetString("ImportPrizeListDesc", resourceCulture);
            }
        }

        public static string PrizeSettings {
            get {
                return ResourceManager.GetString("PrizeSettings", resourceCulture);
            }
        }

        public static string PrizeSettingsDesc {
            get {
                return ResourceManager.GetString("PrizeSettingsDesc", resourceCulture);
            }
        }

        public static string WeightSettings {
            get {
                return ResourceManager.GetString("WeightSettings", resourceCulture);
            }
        }

        public static string WeightSettingsDesc {
            get {
                return ResourceManager.GetString("WeightSettingsDesc", resourceCulture);
            }
        }

        public static string CountSettings {
            get {
                return ResourceManager.GetString("CountSettings", resourceCulture);
            }
        }

        public static string CountSettingsDesc {
            get {
                return ResourceManager.GetString("CountSettingsDesc", resourceCulture);
            }
        }

        public static string ExportPrizeList {
            get {
                return ResourceManager.GetString("ExportPrizeList", resourceCulture);
            }
        }

        public static string ExportPrizeListDesc {
            get {
                return ResourceManager.GetString("ExportPrizeListDesc", resourceCulture);
            }
        }

        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        public static string PreviewTable {
            get {
                return ResourceManager.GetString("PreviewTable", resourceCulture);
            }
        }

        public static string RollCallTableTitle {
            get {
                return ResourceManager.GetString("RollCallTableTitle", resourceCulture);
            }
        }

        public static string LotteryTableTitle {
            get {
                return ResourceManager.GetString("LotteryTableTitle", resourceCulture);
            }
        }

        public static string ColumnExist {
            get {
                return ResourceManager.GetString("ColumnExist", resourceCulture);
            }
        }

        public static string ColumnStudentId {
            get {
                return ResourceManager.GetString("ColumnStudentId", resourceCulture);
            }
        }

        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        public static string ColumnGender {
            get {
                return ResourceManager.GetString("ColumnGender", resourceCulture);
            }
        }

        public static string ColumnGroup {
            get {
                return ResourceManager.GetString("ColumnGroup", resourceCulture);
            }
        }

        public static string ColumnTags {
            get {
                return ResourceManager.GetString("ColumnTags", resourceCulture);
            }
        }

        public static string ColumnSerial {
            get {
                return ResourceManager.GetString("ColumnSerial", resourceCulture);
            }
        }

        public static string ColumnPrize {
            get {
                return ResourceManager.GetString("ColumnPrize", resourceCulture);
            }
        }

        public static string ColumnWeight {
            get {
                return ResourceManager.GetString("ColumnWeight", resourceCulture);
            }
        }

        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }

        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
    }
}
