//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementPage {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagementPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ListManagement {
            get {
                return ResourceManager.GetString("ListManagement", resourceCulture);
            }
        }

        public static string RollCallListSettings {
            get {
                return ResourceManager.GetString("RollCallListSettings", resourceCulture);
            }
        }

        public static string LotteryListSettings {
            get {
                return ResourceManager.GetString("LotteryListSettings", resourceCulture);
            }
        }
        
        public static string ListManagementNavHint {
            get {
                return ResourceManager.GetString("ListManagementNavHint", resourceCulture);
            }
        }

        public static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }

        public static string ClassManagementDesc {
            get {
                return ResourceManager.GetString("ClassManagementDesc", resourceCulture);
            }
        }

        public static string PoolManagement {
            get {
                return ResourceManager.GetString("PoolManagement", resourceCulture);
            }
        }

        public static string PoolManagementDesc {
            get {
                return ResourceManager.GetString("PoolManagementDesc", resourceCulture);
            }
        }

        public static string SetClassName {
            get {
                return ResourceManager.GetString("SetClassName", resourceCulture);
            }
        }

        public static string SetClassNameDesc {
            get {
                return ResourceManager.GetString("SetClassNameDesc", resourceCulture);
            }
        }

        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }

        public static string SelectClassDesc {
            get {
                return ResourceManager.GetString("SelectClassDesc", resourceCulture);
            }
        }

        public static string ImportStudentList {
            get {
                return ResourceManager.GetString("ImportStudentList", resourceCulture);
            }
        }

        public static string ImportStudentListDesc {
            get {
                return ResourceManager.GetString("ImportStudentListDesc", resourceCulture);
            }
        }

        public static string NameSettings {
            get {
                return ResourceManager.GetString("NameSettings", resourceCulture);
            }
        }

        public static string NameSettingsDesc {
            get {
                return ResourceManager.GetString("NameSettingsDesc", resourceCulture);
            }
        }

        public static string GenderSettings {
            get {
                return ResourceManager.GetString("GenderSettings", resourceCulture);
            }
        }

        public static string GenderSettingsDesc {
            get {
                return ResourceManager.GetString("GenderSettingsDesc", resourceCulture);
            }
        }

        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }

        public static string GroupSettingsDesc {
            get {
                return ResourceManager.GetString("GroupSettingsDesc", resourceCulture);
            }
        }

        public static string TagSettings {
            get {
                return ResourceManager.GetString("TagSettings", resourceCulture);
            }
        }

        public static string TagSettingsDesc {
            get {
                return ResourceManager.GetString("TagSettingsDesc", resourceCulture);
            }
        }

        public static string ExportStudentList {
            get {
                return ResourceManager.GetString("ExportStudentList", resourceCulture);
            }
        }

        public static string ExportStudentListDesc {
            get {
                return ResourceManager.GetString("ExportStudentListDesc", resourceCulture);
            }
        }

        public static string SetPoolName {
            get {
                return ResourceManager.GetString("SetPoolName", resourceCulture);
            }
        }

        public static string SetPoolNameDesc {
            get {
                return ResourceManager.GetString("SetPoolNameDesc", resourceCulture);
            }
        }

        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }

        public static string SelectPoolDesc {
            get {
                return ResourceManager.GetString("SelectPoolDesc", resourceCulture);
            }
        }

        public static string ImportPrizeList {
            get {
                return ResourceManager.GetString("ImportPrizeList", resourceCulture);
            }
        }

        public static string ImportPrizeListDesc {
            get {
                return ResourceManager.GetString("ImportPrizeListDesc", resourceCulture);
            }
        }

        public static string PrizeSettings {
            get {
                return ResourceManager.GetString("PrizeSettings", resourceCulture);
            }
        }

        public static string PrizeSettingsDesc {
            get {
                return ResourceManager.GetString("PrizeSettingsDesc", resourceCulture);
            }
        }

        public static string WeightSettings {
            get {
                return ResourceManager.GetString("WeightSettings", resourceCulture);
            }
        }

        public static string WeightSettingsDesc {
            get {
                return ResourceManager.GetString("WeightSettingsDesc", resourceCulture);
            }
        }

        public static string CountSettings {
            get {
                return ResourceManager.GetString("CountSettings", resourceCulture);
            }
        }

        public static string CountSettingsDesc {
            get {
                return ResourceManager.GetString("CountSettingsDesc", resourceCulture);
            }
        }

        public static string ExportPrizeList {
            get {
                return ResourceManager.GetString("ExportPrizeList", resourceCulture);
            }
        }

        public static string ExportPrizeListDesc {
            get {
                return ResourceManager.GetString("ExportPrizeListDesc", resourceCulture);
            }
        }

        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        public static string PreviewTable {
            get {
                return ResourceManager.GetString("PreviewTable", resourceCulture);
            }
        }

        public static string RollCallTableTitle {
            get {
                return ResourceManager.GetString("RollCallTableTitle", resourceCulture);
            }
        }

        public static string LotteryTableTitle {
            get {
                return ResourceManager.GetString("LotteryTableTitle", resourceCulture);
            }
        }

        public static string ColumnExist {
            get {
                return ResourceManager.GetString("ColumnExist", resourceCulture);
            }
        }

        public static string ColumnStudentId {
            get {
                return ResourceManager.GetString("ColumnStudentId", resourceCulture);
            }
        }

        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }

        public static string ColumnGender {
            get {
                return ResourceManager.GetString("ColumnGender", resourceCulture);
            }
        }

        public static string ColumnGroup {
            get {
                return ResourceManager.GetString("ColumnGroup", resourceCulture);
            }
        }

        public static string ColumnTags {
            get {
                return ResourceManager.GetString("ColumnTags", resourceCulture);
            }
        }

        public static string ColumnSerial {
            get {
                return ResourceManager.GetString("ColumnSerial", resourceCulture);
            }
        }

        public static string ColumnPrize {
            get {
                return ResourceManager.GetString("ColumnPrize", resourceCulture);
            }
        }

        public static string ColumnWeight {
            get {
                return ResourceManager.GetString("ColumnWeight", resourceCulture);
            }
        }

        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }

        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        public static string SetPoolNamePageTitle {
            get {
                return ResourceManager.GetString("SetPoolNamePageTitle", resourceCulture);
            }
        }

        public static string CreateNewPool {
            get {
                return ResourceManager.GetString("CreateNewPool", resourceCulture);
            }
        }

        public static string EnterPoolName {
            get {
                return ResourceManager.GetString("EnterPoolName", resourceCulture);
            }
        }

        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        public static string ExistingPools {
            get {
                return ResourceManager.GetString("ExistingPools", resourceCulture);
            }
        }

        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }

        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string ImportPrizePageTitle {
            get {
                return ResourceManager.GetString("ImportPrizePageTitle", resourceCulture);
            }
        }

        public static string SelectPoolLabel {
            get {
                return ResourceManager.GetString("SelectPoolLabel", resourceCulture);
            }
        }

        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }

        public static string SelectFileToImport {
            get {
                return ResourceManager.GetString("SelectFileToImport", resourceCulture);
            }
        }

        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        public static string ImportOptions {
            get {
                return ResourceManager.GetString("ImportOptions", resourceCulture);
            }
        }

        public static string ClearExistingData {
            get {
                return ResourceManager.GetString("ClearExistingData", resourceCulture);
            }
        }

        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }

        public static string JsonFormatDesc {
            get {
                return ResourceManager.GetString("JsonFormatDesc", resourceCulture);
            }
        }

        public static string CsvFormatDesc {
            get {
                return ResourceManager.GetString("CsvFormatDesc", resourceCulture);
            }
        }

        public static string TxtFormatDesc {
            get {
                return ResourceManager.GetString("TxtFormatDesc", resourceCulture);
            }
        }

        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }

        public static string PrizeSettingsPageTitle {
            get {
                return ResourceManager.GetString("PrizeSettingsPageTitle", resourceCulture);
            }
        }

        public static string AddPrize {
            get {
                return ResourceManager.GetString("AddPrize", resourceCulture);
            }
        }

        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }

        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string WeightSettingsPageTitle {
            get {
                return ResourceManager.GetString("WeightSettingsPageTitle", resourceCulture);
            }
        }

        public static string CountSettingsPageTitle {
            get {
                return ResourceManager.GetString("CountSettingsPageTitle", resourceCulture);
            }
        }

        public static string ExportPrizePageTitle {
            get {
                return ResourceManager.GetString("ExportPrizePageTitle", resourceCulture);
            }
        }

        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }

        public static string SelectSaveLocation {
            get {
                return ResourceManager.GetString("SelectSaveLocation", resourceCulture);
            }
        }

        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }

        public static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }

        public static string CsvFormat {
            get {
                return ResourceManager.GetString("CsvFormat", resourceCulture);
            }
        }

        public static string TxtFormat {
            get {
                return ResourceManager.GetString("TxtFormat", resourceCulture);
            }
        }

        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }

        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }

        public static string ColumnEnabled {
            get {
                return ResourceManager.GetString("ColumnEnabled", resourceCulture);
            }
        }

        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }

        public static string PrizeWeight {
            get {
                return ResourceManager.GetString("PrizeWeight", resourceCulture);
            }
        }

        public static string PrizeCount {
            get {
                return ResourceManager.GetString("PrizeCount", resourceCulture);
            }
        }

        public static string EnterPrizeName {
            get {
                return ResourceManager.GetString("EnterPrizeName", resourceCulture);
            }
        }

        public static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }

        public static string EnterCount {
            get {
                return ResourceManager.GetString("EnterCount", resourceCulture);
            }
        }

        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }

        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }

        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }

        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }

        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }

        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string PleaseEnterPoolName {
            get {
                return ResourceManager.GetString("PleaseEnterPoolName", resourceCulture);
            }
        }

        public static string PoolCreatedSuccess {
            get {
                return ResourceManager.GetString("PoolCreatedSuccess", resourceCulture);
            }
        }

        public static string PoolCreateFailed {
            get {
                return ResourceManager.GetString("PoolCreateFailed", resourceCulture);
            }
        }

        public static string RenamePool {
            get {
                return ResourceManager.GetString("RenamePool", resourceCulture);
            }
        }

        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }

        public static string PoolRenamedSuccess {
            get {
                return ResourceManager.GetString("PoolRenamedSuccess", resourceCulture);
            }
        }

        public static string RenameFailed {
            get {
                return ResourceManager.GetString("RenameFailed", resourceCulture);
            }
        }

        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        public static string ConfirmDeletePool {
            get {
                return ResourceManager.GetString("ConfirmDeletePool", resourceCulture);
            }
        }

        public static string PoolDeletedSuccess {
            get {
                return ResourceManager.GetString("PoolDeletedSuccess", resourceCulture);
            }
        }

        public static string DeletePoolFailed {
            get {
                return ResourceManager.GetString("DeletePoolFailed", resourceCulture);
            }
        }

        public static string PleaseCreatePoolFirst {
            get {
                return ResourceManager.GetString("PleaseCreatePoolFirst", resourceCulture);
            }
        }

        public static string PleaseSelectPool {
            get {
                return ResourceManager.GetString("PleaseSelectPool", resourceCulture);
            }
        }

        public static string PleaseSelectValidFile {
            get {
                return ResourceManager.GetString("PleaseSelectValidFile", resourceCulture);
            }
        }

        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }

        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }

        public static string PrizeSettingsSaved {
            get {
                return ResourceManager.GetString("PrizeSettingsSaved", resourceCulture);
            }
        }

        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }

        public static string PleaseSelectPrizeToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectPrizeToDelete", resourceCulture);
            }
        }

        public static string ConfirmDeletePrize {
            get {
                return ResourceManager.GetString("ConfirmDeletePrize", resourceCulture);
            }
        }

        public static string WeightSettingsSaved {
            get {
                return ResourceManager.GetString("WeightSettingsSaved", resourceCulture);
            }
        }

        public static string CountSettingsSaved {
            get {
                return ResourceManager.GetString("CountSettingsSaved", resourceCulture);
            }
        }

        public static string PleaseSelectSaveLocation {
            get {
                return ResourceManager.GetString("PleaseSelectSaveLocation", resourceCulture);
            }
        }

        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }

        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
    }
}
