//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagementPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加奖品.
        /// </summary>
        public static string AddPrize {
            get {
                return ResourceManager.GetString("AddPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 班级管理.
        /// </summary>
        public static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除现有数据（覆盖导入）.
        /// </summary>
        public static string ClearExistingData {
            get {
                return ResourceManager.GetString("ClearExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string ColumnEnabled {
            get {
                return ResourceManager.GetString("ColumnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在.
        /// </summary>
        public static string ColumnExist {
            get {
                return ResourceManager.GetString("ColumnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string ColumnGender {
            get {
                return ResourceManager.GetString("ColumnGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组.
        /// </summary>
        public static string ColumnGroup {
            get {
                return ResourceManager.GetString("ColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品.
        /// </summary>
        public static string ColumnPrize {
            get {
                return ResourceManager.GetString("ColumnPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string ColumnSerial {
            get {
                return ResourceManager.GetString("ColumnSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string ColumnStudentId {
            get {
                return ResourceManager.GetString("ColumnStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string ColumnTags {
            get {
                return ResourceManager.GetString("ColumnTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string ColumnWeight {
            get {
                return ResourceManager.GetString("ColumnWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除奖池 &apos;{0}&apos; 吗？此操作不可撤销。.
        /// </summary>
        public static string ConfirmDeletePool {
            get {
                return ResourceManager.GetString("ConfirmDeletePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除奖品 &apos;{0}&apos; 吗？.
        /// </summary>
        public static string ConfirmDeletePrize {
            get {
                return ResourceManager.GetString("ConfirmDeletePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量：.
        /// </summary>
        public static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置数量.
        /// </summary>
        public static string CountSettings {
            get {
                return ResourceManager.GetString("CountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量设置.
        /// </summary>
        public static string CountSettingsPageTitle {
            get {
                return ResourceManager.GetString("CountSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量设置已保存.
        /// </summary>
        public static string CountSettingsSaved {
            get {
                return ResourceManager.GetString("CountSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新奖池.
        /// </summary>
        public static string CreateNewPool {
            get {
                return ResourceManager.GetString("CreateNewPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV 格式.
        /// </summary>
        public static string CsvFormat {
            get {
                return ResourceManager.GetString("CsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV - 名称,权重,数量,标签.
        /// </summary>
        public static string CsvFormatDesc {
            get {
                return ResourceManager.GetString("CsvFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除奖池失败.
        /// </summary>
        public static string DeletePoolFailed {
            get {
                return ResourceManager.GetString("DeletePoolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string EnterCount {
            get {
                return ResourceManager.GetString("EnterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新名称.
        /// </summary>
        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新奖池名称.
        /// </summary>
        public static string EnterPoolName {
            get {
                return ResourceManager.GetString("EnterPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品名称.
        /// </summary>
        public static string EnterPrizeName {
            get {
                return ResourceManager.GetString("EnterPrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现有奖池.
        /// </summary>
        public static string ExistingPools {
            get {
                return ResourceManager.GetString("ExistingPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出格式.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出奖品名单.
        /// </summary>
        public static string ExportPrizeList {
            get {
                return ResourceManager.GetString("ExportPrizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出奖品名单.
        /// </summary>
        public static string ExportPrizePageTitle {
            get {
                return ResourceManager.GetString("ExportPrizePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出学生名单.
        /// </summary>
        public static string ExportStudentList {
            get {
                return ResourceManager.GetString("ExportStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品名单已导出到：{0}.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置性别.
        /// </summary>
        public static string GenderSettings {
            get {
                return ResourceManager.GetString("GenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置小组.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入失败，请检查文件格式是否正确.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入选项.
        /// </summary>
        public static string ImportOptions {
            get {
                return ResourceManager.GetString("ImportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入奖品名单.
        /// </summary>
        public static string ImportPrizeList {
            get {
                return ResourceManager.GetString("ImportPrizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入奖品名单.
        /// </summary>
        public static string ImportPrizePageTitle {
            get {
                return ResourceManager.GetString("ImportPrizePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入学生名单.
        /// </summary>
        public static string ImportStudentList {
            get {
                return ResourceManager.GetString("ImportStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功导入 {0} 个奖品.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 格式.
        /// </summary>
        public static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON - 奖池格式文件.
        /// </summary>
        public static string JsonFormatDesc {
            get {
                return ResourceManager.GetString("JsonFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名单管理.
        /// </summary>
        public static string ListManagement {
            get {
                return ResourceManager.GetString("ListManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在左侧导航栏选择具体设置.
        /// </summary>
        public static string ListManagementNavHint {
            get {
                return ResourceManager.GetString("ListManagementNavHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖名单.
        /// </summary>
        public static string LotteryListSettings {
            get {
                return ResourceManager.GetString("LotteryListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖表格.
        /// </summary>
        public static string LotteryTableTitle {
            get {
                return ResourceManager.GetString("LotteryTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称：.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置姓名.
        /// </summary>
        public static string NameSettings {
            get {
                return ResourceManager.GetString("NameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先创建奖池.
        /// </summary>
        public static string PleaseCreatePoolFirst {
            get {
                return ResourceManager.GetString("PleaseCreatePoolFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入奖池名称.
        /// </summary>
        public static string PleaseEnterPoolName {
            get {
                return ResourceManager.GetString("PleaseEnterPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择奖池.
        /// </summary>
        public static string PleaseSelectPool {
            get {
                return ResourceManager.GetString("PleaseSelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择要删除的奖品.
        /// </summary>
        public static string PleaseSelectPrizeToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectPrizeToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择保存位置.
        /// </summary>
        public static string PleaseSelectSaveLocation {
            get {
                return ResourceManager.GetString("PleaseSelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择有效的文件.
        /// </summary>
        public static string PleaseSelectValidFile {
            get {
                return ResourceManager.GetString("PleaseSelectValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池 &apos;{0}&apos; 创建成功.
        /// </summary>
        public static string PoolCreatedSuccess {
            get {
                return ResourceManager.GetString("PoolCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建奖池失败，可能名称已存在.
        /// </summary>
        public static string PoolCreateFailed {
            get {
                return ResourceManager.GetString("PoolCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池 &apos;{0}&apos; 已删除.
        /// </summary>
        public static string PoolDeletedSuccess {
            get {
                return ResourceManager.GetString("PoolDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池管理.
        /// </summary>
        public static string PoolManagement {
            get {
                return ResourceManager.GetString("PoolManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池已重命名为 &apos;{0}&apos;.
        /// </summary>
        public static string PoolRenamedSuccess {
            get {
                return ResourceManager.GetString("PoolRenamedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览表格.
        /// </summary>
        public static string PreviewTable {
            get {
                return ResourceManager.GetString("PreviewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string PrizeCount {
            get {
                return ResourceManager.GetString("PrizeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品名称.
        /// </summary>
        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品.
        /// </summary>
        public static string PrizeSettings {
            get {
                return ResourceManager.GetString("PrizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品设置.
        /// </summary>
        public static string PrizeSettingsPageTitle {
            get {
                return ResourceManager.GetString("PrizeSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品设置已保存.
        /// </summary>
        public static string PrizeSettingsSaved {
            get {
                return ResourceManager.GetString("PrizeSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string PrizeWeight {
            get {
                return ResourceManager.GetString("PrizeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名失败，可能名称已存在.
        /// </summary>
        public static string RenameFailed {
            get {
                return ResourceManager.GetString("RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名奖池.
        /// </summary>
        public static string RenamePool {
            get {
                return ResourceManager.GetString("RenamePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名名单.
        /// </summary>
        public static string RollCallListSettings {
            get {
                return ResourceManager.GetString("RollCallListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名表格.
        /// </summary>
        public static string RollCallTableTitle {
            get {
                return ResourceManager.GetString("RollCallTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存位置.
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择班级.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从已有班级中选择一个班级.
        /// </summary>
        public static string SelectClassDesc {
            get {
                return ResourceManager.GetString("SelectClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要导入的文件.
        /// </summary>
        public static string SelectFileToImport {
            get {
                return ResourceManager.GetString("SelectFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从已有奖池中选择一个奖池.
        /// </summary>
        public static string SelectPoolDesc {
            get {
                return ResourceManager.GetString("SelectPoolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string SelectPoolLabel {
            get {
                return ResourceManager.GetString("SelectPoolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择保存位置.
        /// </summary>
        public static string SelectSaveLocation {
            get {
                return ResourceManager.GetString("SelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置班级名称.
        /// </summary>
        public static string SetClassName {
            get {
                return ResourceManager.GetString("SetClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖池名称.
        /// </summary>
        public static string SetPoolName {
            get {
                return ResourceManager.GetString("SetPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池名称设置.
        /// </summary>
        public static string SetPoolNamePageTitle {
            get {
                return ResourceManager.GetString("SetPoolNamePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理点名用学生名单.
        /// </summary>
        public static string Settings_ClassManagementDesc {
            get {
                return ResourceManager.GetString("Settings_ClassManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品中奖数量.
        /// </summary>
        public static string Settings_CountSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_CountSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将奖品名单导出到文件.
        /// </summary>
        public static string Settings_ExportPrizeListDesc {
            get {
                return ResourceManager.GetString("Settings_ExportPrizeListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将学生名单导出到文件.
        /// </summary>
        public static string Settings_ExportStudentListDesc {
            get {
                return ResourceManager.GetString("Settings_ExportStudentListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生性别.
        /// </summary>
        public static string Settings_GenderSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GenderSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生所属小组.
        /// </summary>
        public static string Settings_GroupSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GroupSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入奖品名单.
        /// </summary>
        public static string Settings_ImportPrizeListDesc {
            get {
                return ResourceManager.GetString("Settings_ImportPrizeListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入学生名单.
        /// </summary>
        public static string Settings_ImportStudentListDesc {
            get {
                return ResourceManager.GetString("Settings_ImportStudentListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生姓名.
        /// </summary>
        public static string Settings_NameSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_NameSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理抽奖用奖品名单.
        /// </summary>
        public static string Settings_PoolManagementDesc {
            get {
                return ResourceManager.GetString("Settings_PoolManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品名称.
        /// </summary>
        public static string Settings_PrizeSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_PrizeSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置当前班级名称.
        /// </summary>
        public static string Settings_SetClassNameDesc {
            get {
                return ResourceManager.GetString("Settings_SetClassNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置当前奖池名称.
        /// </summary>
        public static string Settings_SetPoolNameDesc {
            get {
                return ResourceManager.GetString("Settings_SetPoolNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生标签.
        /// </summary>
        public static string Settings_TagSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_TagSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品中奖权重.
        /// </summary>
        public static string Settings_WeightSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_WeightSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始导出.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始导入.
        /// </summary>
        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持的文件格式：.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签设置.
        /// </summary>
        public static string TagSettings {
            get {
                return ResourceManager.GetString("TagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT 格式（仅名称）.
        /// </summary>
        public static string TxtFormat {
            get {
                return ResourceManager.GetString("TxtFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT - 每行一个奖品名称.
        /// </summary>
        public static string TxtFormatDesc {
            get {
                return ResourceManager.GetString("TxtFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重：.
        /// </summary>
        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置权重.
        /// </summary>
        public static string WeightSettings {
            get {
                return ResourceManager.GetString("WeightSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重设置.
        /// </summary>
        public static string WeightSettingsPageTitle {
            get {
                return ResourceManager.GetString("WeightSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重设置已保存.
        /// </summary>
        public static string WeightSettingsSaved {
            get {
                return ResourceManager.GetString("WeightSettingsSaved", resourceCulture);
            }
        }
    }
}
