//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.NotificationSettingsPage {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.NotificationSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string TitleDesc {
            get {
                return ResourceManager.GetString("TitleDesc", resourceCulture);
            }
        }
        
        public static string RollCallNotificationSettings {
            get {
                return ResourceManager.GetString("RollCallNotificationSettings", resourceCulture);
            }
        }
        
        public static string QuickDrawNotificationSettings {
            get {
                return ResourceManager.GetString("QuickDrawNotificationSettings", resourceCulture);
            }
        }
        
        public static string LotteryNotificationSettings {
            get {
                return ResourceManager.GetString("LotteryNotificationSettings", resourceCulture);
            }
        }
        
        public static string RollCallNotificationTitle {
            get {
                return ResourceManager.GetString("RollCallNotificationTitle", resourceCulture);
            }
        }
        
        public static string RollCallNotificationTitleDesc {
            get {
                return ResourceManager.GetString("RollCallNotificationTitleDesc", resourceCulture);
            }
        }
        
        public static string QuickDrawNotificationTitle {
            get {
                return ResourceManager.GetString("QuickDrawNotificationTitle", resourceCulture);
            }
        }
        
        public static string QuickDrawNotificationTitleDesc {
            get {
                return ResourceManager.GetString("QuickDrawNotificationTitleDesc", resourceCulture);
            }
        }
        
        public static string LotteryNotificationTitle {
            get {
                return ResourceManager.GetString("LotteryNotificationTitle", resourceCulture);
            }
        }
        
        public static string LotteryNotificationTitleDesc {
            get {
                return ResourceManager.GetString("LotteryNotificationTitleDesc", resourceCulture);
            }
        }
        
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        public static string BasicSettingsDesc {
            get {
                return ResourceManager.GetString("BasicSettingsDesc", resourceCulture);
            }
        }
        
        public static string FloatingWindowMode {
            get {
                return ResourceManager.GetString("FloatingWindowMode", resourceCulture);
            }
        }
        
        public static string FloatingWindowModeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowModeDesc", resourceCulture);
            }
        }
        
        public static string ClassIslandNotificationServiceSettings {
            get {
                return ResourceManager.GetString("ClassIslandNotificationServiceSettings", resourceCulture);
            }
        }
        
        public static string ClassIslandNotificationServiceSettingsDesc {
            get {
                return ResourceManager.GetString("ClassIslandNotificationServiceSettingsDesc", resourceCulture);
            }
        }
        
        public static string CallNotificationService {
            get {
                return ResourceManager.GetString("CallNotificationService", resourceCulture);
            }
        }
        
        public static string CallNotificationServiceDesc {
            get {
                return ResourceManager.GetString("CallNotificationServiceDesc", resourceCulture);
            }
        }
        
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        public static string AnimationDesc {
            get {
                return ResourceManager.GetString("AnimationDesc", resourceCulture);
            }
        }
        
        public static string FloatingWindowEnabledMonitor {
            get {
                return ResourceManager.GetString("FloatingWindowEnabledMonitor", resourceCulture);
            }
        }
        
        public static string FloatingWindowEnabledMonitorDesc {
            get {
                return ResourceManager.GetString("FloatingWindowEnabledMonitorDesc", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition {
            get {
                return ResourceManager.GetString("FloatingWindowPosition", resourceCulture);
            }
        }
        
        public static string FloatingWindowPositionDesc {
            get {
                return ResourceManager.GetString("FloatingWindowPositionDesc", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition0 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition0", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition1 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition1", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition2 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition2", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition3 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition3", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition4 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition4", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition5 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition5", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition6 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition6", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition7 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition7", resourceCulture);
            }
        }
        
        public static string FloatingWindowPosition8 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition8", resourceCulture);
            }
        }
        
        public static string FloatingWindowHorizontalOffset {
            get {
                return ResourceManager.GetString("FloatingWindowHorizontalOffset", resourceCulture);
            }
        }

        public static string FloatingWindowHorizontalOffsetDesc {
            get {
                return ResourceManager.GetString("FloatingWindowHorizontalOffsetDesc", resourceCulture);
            }
        }

        public static string FloatingWindowVerticalOffset {
            get {
                return ResourceManager.GetString("FloatingWindowVerticalOffset", resourceCulture);
            }
        }

        public static string FloatingWindowVerticalOffsetDesc {
            get {
                return ResourceManager.GetString("FloatingWindowVerticalOffsetDesc", resourceCulture);
            }
        }

        public static string FloatingWindowTransparency {
            get {
                return ResourceManager.GetString("FloatingWindowTransparency", resourceCulture);
            }
        }

        public static string FloatingWindowTransparencyDesc {
            get {
                return ResourceManager.GetString("FloatingWindowTransparencyDesc", resourceCulture);
            }
        }

        public static string FloatingWindowAutoCloseTime {
            get {
                return ResourceManager.GetString("FloatingWindowAutoCloseTime", resourceCulture);
            }
        }

        public static string FloatingWindowAutoCloseTimeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowAutoCloseTimeDesc", resourceCulture);
            }
        }

        public static string UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }

        public static string UseMainWindowWhenExceedThresholdDesc {
            get {
                return ResourceManager.GetString("UseMainWindowWhenExceedThresholdDesc", resourceCulture);
            }
        }

        public static string MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("MainWindowDisplayThreshold", resourceCulture);
            }
        }

        public static string MainWindowDisplayThresholdDesc {
            get {
                return ResourceManager.GetString("MainWindowDisplayThresholdDesc", resourceCulture);
            }
        }
        
        public static string NotificationServiceType {
            get {
                return ResourceManager.GetString("NotificationServiceType", resourceCulture);
            }
        }

        public static string NotificationServiceTypeDesc {
            get {
                return ResourceManager.GetString("NotificationServiceTypeDesc", resourceCulture);
            }
        }

        public static string NotificationServiceType0 {
            get {
                return ResourceManager.GetString("NotificationServiceType0", resourceCulture);
            }
        }
        
        public static string NotificationServiceType1 {
            get {
                return ResourceManager.GetString("NotificationServiceType1", resourceCulture);
            }
        }
        
        public static string NotificationServiceType2 {
            get {
                return ResourceManager.GetString("NotificationServiceType2", resourceCulture);
            }
        }
        
        public static string NotificationDisplayDuration {
            get {
                return ResourceManager.GetString("NotificationDisplayDuration", resourceCulture);
            }
        }

        public static string NotificationDisplayDurationDesc {
            get {
                return ResourceManager.GetString("NotificationDisplayDurationDesc", resourceCulture);
            }
        }
    }
}
