//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.NotificationSettingsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.NotificationSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画效果.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制通知窗口动画效果显示.
        /// </summary>
        public static string AnimationDesc {
            get {
                return ResourceManager.GetString("AnimationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用通知服务.
        /// </summary>
        public static string CallNotificationService {
            get {
                return ResourceManager.GetString("CallNotificationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到ClassIsland和SecRandom-Ci插件正常运行，欢迎使用.
        /// </summary>
        public static string ClassIslandConfiguredSuccessfullyContent {
            get {
                return ResourceManager.GetString("ClassIslandConfiguredSuccessfullyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland通知服务.
        /// </summary>
        public static string ClassIslandConfiguredSuccessfullyTitle {
            get {
                return ResourceManager.GetString("ClassIslandConfiguredSuccessfullyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确保已安装.NET 8运行时，并在ClassIsland中安装SecRandom-Ci插件.
        /// </summary>
        public static string ClassIslandNotificationHintContent {
            get {
                return ResourceManager.GetString("ClassIslandNotificationHintContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland通知服务.
        /// </summary>
        public static string ClassIslandNotificationHintTitle {
            get {
                return ResourceManager.GetString("ClassIslandNotificationHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland通知服务.
        /// </summary>
        public static string ClassIslandNotificationServiceSettings {
            get {
                return ResourceManager.GetString("ClassIslandNotificationServiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到未安装插件，请在ClassIsland中安装SecRandom-Ci插件.
        /// </summary>
        public static string ClassIslandPluginNotificationHintContent {
            get {
                return ResourceManager.GetString("ClassIslandPluginNotificationHintContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland通知服务.
        /// </summary>
        public static string ClassIslandPluginNotificationHintTitle {
            get {
                return ResourceManager.GetString("ClassIslandPluginNotificationHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无焦点模式.
        /// </summary>
        public static string DoNotStealFocus {
            get {
                return ResourceManager.GetString("DoNotStealFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成后不抢占焦点，保持原有顶层软件焦点.
        /// </summary>
        public static string DoNotStealFocusDesc {
            get {
                return ResourceManager.GetString("DoNotStealFocusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗自动关闭时间.
        /// </summary>
        public static string FloatingWindowAutoCloseTime {
            get {
                return ResourceManager.GetString("FloatingWindowAutoCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示器选择.
        /// </summary>
        public static string FloatingWindowEnabledMonitor {
            get {
                return ResourceManager.GetString("FloatingWindowEnabledMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平偏移.
        /// </summary>
        public static string FloatingWindowHorizontalOffset {
            get {
                return ResourceManager.GetString("FloatingWindowHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗模式.
        /// </summary>
        public static string FloatingWindowMode {
            get {
                return ResourceManager.GetString("FloatingWindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置通知浮窗行为.
        /// </summary>
        public static string FloatingWindowModeDesc {
            get {
                return ResourceManager.GetString("FloatingWindowModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗位置.
        /// </summary>
        public static string FloatingWindowPosition {
            get {
                return ResourceManager.GetString("FloatingWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中心.
        /// </summary>
        public static string FloatingWindowPosition0 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部.
        /// </summary>
        public static string FloatingWindowPosition1 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部.
        /// </summary>
        public static string FloatingWindowPosition2 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左侧.
        /// </summary>
        public static string FloatingWindowPosition3 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右侧.
        /// </summary>
        public static string FloatingWindowPosition4 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部左侧.
        /// </summary>
        public static string FloatingWindowPosition5 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部右侧.
        /// </summary>
        public static string FloatingWindowPosition6 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部左侧.
        /// </summary>
        public static string FloatingWindowPosition7 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部右侧.
        /// </summary>
        public static string FloatingWindowPosition8 {
            get {
                return ResourceManager.GetString("FloatingWindowPosition8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置通知浮窗屏幕显示位置.
        /// </summary>
        public static string FloatingWindowPositionDesc {
            get {
                return ResourceManager.GetString("FloatingWindowPositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度.
        /// </summary>
        public static string FloatingWindowTransparency {
            get {
                return ResourceManager.GetString("FloatingWindowTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直偏移.
        /// </summary>
        public static string FloatingWindowVerticalOffset {
            get {
                return ResourceManager.GetString("FloatingWindowVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知.
        /// </summary>
        public static string LotteryNotificationSettings {
            get {
                return ResourceManager.GetString("LotteryNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知设置.
        /// </summary>
        public static string LotteryNotificationTitle {
            get {
                return ResourceManager.GetString("LotteryNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置抽奖结果通知显示方式和参数.
        /// </summary>
        public static string LotteryNotificationTitleDesc {
            get {
                return ResourceManager.GetString("LotteryNotificationTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗通知阈值.
        /// </summary>
        public static string MainWindowDisplayThreshold {
            get {
                return ResourceManager.GetString("MainWindowDisplayThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置触发浮窗通知的人数阈值，超过此数值则不显示浮窗通知，最小值为1.
        /// </summary>
        public static string MainWindowDisplayThresholdDesc {
            get {
                return ResourceManager.GetString("MainWindowDisplayThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知显示时长.
        /// </summary>
        public static string NotificationDisplayDuration {
            get {
                return ResourceManager.GetString("NotificationDisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知服务类型.
        /// </summary>
        public static string NotificationServiceType {
            get {
                return ResourceManager.GetString("NotificationServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecRandom.
        /// </summary>
        public static string NotificationServiceType0 {
            get {
                return ResourceManager.GetString("NotificationServiceType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland.
        /// </summary>
        public static string NotificationServiceType1 {
            get {
                return ResourceManager.GetString("NotificationServiceType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecRandom+ClassIsland.
        /// </summary>
        public static string NotificationServiceType2 {
            get {
                return ResourceManager.GetString("NotificationServiceType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知.
        /// </summary>
        public static string QuickDrawNotificationSettings {
            get {
                return ResourceManager.GetString("QuickDrawNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知设置.
        /// </summary>
        public static string QuickDrawNotificationTitle {
            get {
                return ResourceManager.GetString("QuickDrawNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置闪抽结果通知显示方式和参数.
        /// </summary>
        public static string QuickDrawNotificationTitleDesc {
            get {
                return ResourceManager.GetString("QuickDrawNotificationTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知.
        /// </summary>
        public static string RollCallNotificationSettings {
            get {
                return ResourceManager.GetString("RollCallNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知设置.
        /// </summary>
        public static string RollCallNotificationTitle {
            get {
                return ResourceManager.GetString("RollCallNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知功能设置.
        /// </summary>
        public static string RollCallNotificationTitleDesc {
            get {
                return ResourceManager.GetString("RollCallNotificationTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置通知显示基础参数.
        /// </summary>
        public static string Settings_BasicSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_BasicSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后调用系统通知服务发送结果.
        /// </summary>
        public static string Settings_CallNotificationServiceDesc {
            get {
                return ResourceManager.GetString("Settings_CallNotificationServiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置ClassIsland通知服务参数.
        /// </summary>
        public static string Settings_ClassIslandNotificationServiceSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_ClassIslandNotificationServiceSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置浮窗自动关闭时间（秒），设为0表示不自动关闭.
        /// </summary>
        public static string Settings_FloatingWindowAutoCloseTimeDesc {
            get {
                return ResourceManager.GetString("Settings_FloatingWindowAutoCloseTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择显示通知浮窗的显示器.
        /// </summary>
        public static string Settings_FloatingWindowEnabledMonitorDesc {
            get {
                return ResourceManager.GetString("Settings_FloatingWindowEnabledMonitorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整通知浮窗相对默认位置水平偏移量（像素）.
        /// </summary>
        public static string Settings_FloatingWindowHorizontalOffsetDesc {
            get {
                return ResourceManager.GetString("Settings_FloatingWindowHorizontalOffsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整通知浮窗透明度，数值越小越透明（0-100）.
        /// </summary>
        public static string Settings_FloatingWindowTransparencyDesc {
            get {
                return ResourceManager.GetString("Settings_FloatingWindowTransparencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整通知浮窗相对默认位置垂直偏移量（像素）.
        /// </summary>
        public static string Settings_FloatingWindowVerticalOffsetDesc {
            get {
                return ResourceManager.GetString("Settings_FloatingWindowVerticalOffsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置ClassIsland通知显示时长（秒）.
        /// </summary>
        public static string Settings_NotificationDisplayDurationDesc {
            get {
                return ResourceManager.GetString("Settings_NotificationDisplayDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择通知服务类型，SecRandom或ClassIsland.
        /// </summary>
        public static string Settings_NotificationServiceTypeDesc {
            get {
                return ResourceManager.GetString("Settings_NotificationServiceTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当抽取人数超过设定阈值时，不显示浮窗通知，只在主窗口显示结果.
        /// </summary>
        public static string Settings_UseMainWindowWhenExceedThresholdDesc {
            get {
                return ResourceManager.GetString("Settings_UseMainWindowWhenExceedThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知设置.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知功能设置.
        /// </summary>
        public static string TitleDesc {
            get {
                return ResourceManager.GetString("TitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超过阈值时不显示浮窗通知.
        /// </summary>
        public static string UseMainWindowWhenExceedThreshold {
            get {
                return ResourceManager.GetString("UseMainWindowWhenExceedThreshold", resourceCulture);
            }
        }
    }
}
