//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.HistoryPage {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.HistoryPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }

        public static string HistoryManagement {
            get {
                return ResourceManager.GetString("HistoryManagement", resourceCulture);
            }
        }

        public static string HistoryManagementDesc {
            get {
                return ResourceManager.GetString("HistoryManagementDesc", resourceCulture);
            }
        }

        public static string RollCallHistory {
            get {
                return ResourceManager.GetString("RollCallHistory", resourceCulture);
            }
        }

        public static string RollCallHistoryDesc {
            get {
                return ResourceManager.GetString("RollCallHistoryDesc", resourceCulture);
            }
        }

        public static string LotteryHistory {
            get {
                return ResourceManager.GetString("LotteryHistory", resourceCulture);
            }
        }

        public static string LotteryHistoryDesc {
            get {
                return ResourceManager.GetString("LotteryHistoryDesc", resourceCulture);
            }
        }

        public static string EnableRollCallHistory {
            get {
                return ResourceManager.GetString("EnableRollCallHistory", resourceCulture);
            }
        }

        public static string EnableRollCallHistoryDesc {
            get {
                return ResourceManager.GetString("EnableRollCallHistoryDesc", resourceCulture);
            }
        }

        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }

        public static string SelectClassDesc {
            get {
                return ResourceManager.GetString("SelectClassDesc", resourceCulture);
            }
        }

        public static string ClearRollCallHistory {
            get {
                return ResourceManager.GetString("ClearRollCallHistory", resourceCulture);
            }
        }

        public static string ClearRollCallHistoryDesc {
            get {
                return ResourceManager.GetString("ClearRollCallHistoryDesc", resourceCulture);
            }
        }

        public static string EnableLotteryHistory {
            get {
                return ResourceManager.GetString("EnableLotteryHistory", resourceCulture);
            }
        }

        public static string EnableLotteryHistoryDesc {
            get {
                return ResourceManager.GetString("EnableLotteryHistoryDesc", resourceCulture);
            }
        }

        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }

        public static string SelectPoolDesc {
            get {
                return ResourceManager.GetString("SelectPoolDesc", resourceCulture);
            }
        }

        public static string ClearLotteryHistory {
            get {
                return ResourceManager.GetString("ClearLotteryHistory", resourceCulture);
            }
        }

        public static string ClearLotteryHistoryDesc {
            get {
                return ResourceManager.GetString("ClearLotteryHistoryDesc", resourceCulture);
            }
        }

        public static string RollCallHistoryTable {
            get {
                return ResourceManager.GetString("RollCallHistoryTable", resourceCulture);
            }
        }

        public static string RollCallHistoryTableDesc {
            get {
                return ResourceManager.GetString("RollCallHistoryTableDesc", resourceCulture);
            }
        }

        public static string LotteryHistoryTable {
            get {
                return ResourceManager.GetString("LotteryHistoryTable", resourceCulture);
            }
        }

        public static string LotteryHistoryTableDesc {
            get {
                return ResourceManager.GetString("LotteryHistoryTableDesc", resourceCulture);
            }
        }

        public static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }

        public static string ViewModeDesc {
            get {
                return ResourceManager.GetString("ViewModeDesc", resourceCulture);
            }
        }

        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }

        public static string SelectSubjectDesc {
            get {
                return ResourceManager.GetString("SelectSubjectDesc", resourceCulture);
            }
        }

        public static string ShowWeight {
            get {
                return ResourceManager.GetString("ShowWeight", resourceCulture);
            }
        }

        public static string ShowWeightDesc {
            get {
                return ResourceManager.GetString("ShowWeightDesc", resourceCulture);
            }
        }

        public static string AllHistory {
            get {
                return ResourceManager.GetString("AllHistory", resourceCulture);
            }
        }

        public static string ViewByTime {
            get {
                return ResourceManager.GetString("ViewByTime", resourceCulture);
            }
        }

        public static string AllSubjects {
            get {
                return ResourceManager.GetString("AllSubjects", resourceCulture);
            }
        }

        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }

        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }

        public static string PickingTimes {
            get {
                return ResourceManager.GetString("PickingTimes", resourceCulture);
            }
        }

        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }

        public static string PickingTime {
            get {
                return ResourceManager.GetString("PickingTime", resourceCulture);
            }
        }

        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        public static string PickingMode {
            get {
                return ResourceManager.GetString("PickingMode", resourceCulture);
            }
        }

        public static string PickingAmount {
            get {
                return ResourceManager.GetString("PickingAmount", resourceCulture);
            }
        }

        public static string GenderLimit {
            get {
                return ResourceManager.GetString("GenderLimit", resourceCulture);
            }
        }

        public static string GroupLimit {
            get {
                return ResourceManager.GetString("GroupLimit", resourceCulture);
            }
        }

        public static string RandomPick {
            get {
                return ResourceManager.GetString("RandomPick", resourceCulture);
            }
        }

        public static string FairPick {
            get {
                return ResourceManager.GetString("FairPick", resourceCulture);
            }
        }

        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }

        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }

        public static string WinningTimes {
            get {
                return ResourceManager.GetString("WinningTimes", resourceCulture);
            }
        }

        public static string LotteryTime {
            get {
                return ResourceManager.GetString("LotteryTime", resourceCulture);
            }
        }

        public static string LotteryAmount {
            get {
                return ResourceManager.GetString("LotteryAmount", resourceCulture);
            }
        }

        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }

        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string ConfirmClearRollCallHistory {
            get {
                return ResourceManager.GetString("ConfirmClearRollCallHistory", resourceCulture);
            }
        }

        public static string ConfirmClearLotteryHistory {
            get {
                return ResourceManager.GetString("ConfirmClearLotteryHistory", resourceCulture);
            }
        }

        public static string ClearRollCallHistorySuccess {
            get {
                return ResourceManager.GetString("ClearRollCallHistorySuccess", resourceCulture);
            }
        }

        public static string ClearLotteryHistorySuccess {
            get {
                return ResourceManager.GetString("ClearLotteryHistorySuccess", resourceCulture);
            }
        }

        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }

        public static string ViewHistoryDesc {
            get {
                return ResourceManager.GetString("ViewHistoryDesc", resourceCulture);
            }
        }
    }
}
