//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.HistoryPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.HistoryPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部记录.
        /// </summary>
        public static string AllHistory {
            get {
                return ResourceManager.GetString("AllHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部课程.
        /// </summary>
        public static string AllSubjects {
            get {
                return ResourceManager.GetString("AllSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除抽奖历史记录.
        /// </summary>
        public static string ClearLotteryHistory {
            get {
                return ResourceManager.GetString("ClearLotteryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池 &apos;{name}&apos; 的抽奖历史记录已成功清除。.
        /// </summary>
        public static string ClearLotteryHistorySuccess {
            get {
                return ResourceManager.GetString("ClearLotteryHistorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除点名历史记录.
        /// </summary>
        public static string ClearRollCallHistory {
            get {
                return ResourceManager.GetString("ClearRollCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 班级 &apos;{name}&apos; 的点名历史记录已成功清除。.
        /// </summary>
        public static string ClearRollCallHistorySuccess {
            get {
                return ResourceManager.GetString("ClearRollCallHistorySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要清除奖池 &apos;{name}&apos; 的抽奖历史记录吗？此操作不可恢复。.
        /// </summary>
        public static string ConfirmClearLotteryHistory {
            get {
                return ResourceManager.GetString("ConfirmClearLotteryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要清除班级 &apos;{name}&apos; 的点名历史记录吗？此操作不可恢复。.
        /// </summary>
        public static string ConfirmClearRollCallHistory {
            get {
                return ResourceManager.GetString("ConfirmClearRollCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用抽奖历史记录.
        /// </summary>
        public static string EnableLotteryHistory {
            get {
                return ResourceManager.GetString("EnableLotteryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用点名历史记录.
        /// </summary>
        public static string EnableRollCallHistory {
            get {
                return ResourceManager.GetString("EnableRollCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公平抽取.
        /// </summary>
        public static string FairPick {
            get {
                return ResourceManager.GetString("FairPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别限制.
        /// </summary>
        public static string GenderLimit {
            get {
                return ResourceManager.GetString("GenderLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小组限制.
        /// </summary>
        public static string GroupLimit {
            get {
                return ResourceManager.GetString("GroupLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录管理.
        /// </summary>
        public static string HistoryManagement {
            get {
                return ResourceManager.GetString("HistoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取数量.
        /// </summary>
        public static string LotteryAmount {
            get {
                return ResourceManager.GetString("LotteryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖历史记录表格.
        /// </summary>
        public static string LotteryHistoryTable {
            get {
                return ResourceManager.GetString("LotteryHistoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖时间.
        /// </summary>
        public static string LotteryTime {
            get {
                return ResourceManager.GetString("LotteryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名人数.
        /// </summary>
        public static string PickingAmount {
            get {
                return ResourceManager.GetString("PickingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名模式.
        /// </summary>
        public static string PickingMode {
            get {
                return ResourceManager.GetString("PickingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名时间.
        /// </summary>
        public static string PickingTime {
            get {
                return ResourceManager.GetString("PickingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名次数.
        /// </summary>
        public static string PickingTimes {
            get {
                return ResourceManager.GetString("PickingTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机抽取.
        /// </summary>
        public static string RandomPick {
            get {
                return ResourceManager.GetString("RandomPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名历史记录表格.
        /// </summary>
        public static string RollCallHistoryTable {
            get {
                return ResourceManager.GetString("RollCallHistoryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择班级.
        /// </summary>
        public static string SelectClass {
            get {
                return ResourceManager.GetString("SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要查看历史记录的班级.
        /// </summary>
        public static string SelectClassDesc {
            get {
                return ResourceManager.GetString("SelectClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要查看历史记录的奖池.
        /// </summary>
        public static string SelectPoolDesc {
            get {
                return ResourceManager.GetString("SelectPoolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择课程.
        /// </summary>
        public static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除选定奖池的抽奖历史记录.
        /// </summary>
        public static string Settings_ClearLotteryHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_ClearLotteryHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除选定班级的点名历史记录.
        /// </summary>
        public static string Settings_ClearRollCallHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_ClearRollCallHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制是否启用抽奖历史记录功能.
        /// </summary>
        public static string Settings_EnableLotteryHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_EnableLotteryHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制是否启用点名历史记录功能.
        /// </summary>
        public static string Settings_EnableRollCallHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_EnableRollCallHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理点名、抽奖的历史记录.
        /// </summary>
        public static string Settings_HistoryManagementDesc {
            get {
                return ResourceManager.GetString("Settings_HistoryManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖历史记录.
        /// </summary>
        public static string Settings_LotteryHistory {
            get {
                return ResourceManager.GetString("Settings_LotteryHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看和管理抽奖的历史记录.
        /// </summary>
        public static string Settings_LotteryHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_LotteryHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以表格形式展示抽奖的历史记录.
        /// </summary>
        public static string Settings_LotteryHistoryTableDesc {
            get {
                return ResourceManager.GetString("Settings_LotteryHistoryTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名历史记录.
        /// </summary>
        public static string Settings_RollCallHistory {
            get {
                return ResourceManager.GetString("Settings_RollCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看和管理点名的历史记录.
        /// </summary>
        public static string Settings_RollCallHistoryDesc {
            get {
                return ResourceManager.GetString("Settings_RollCallHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以表格形式展示点名的历史记录.
        /// </summary>
        public static string Settings_RollCallHistoryTableDesc {
            get {
                return ResourceManager.GetString("Settings_RollCallHistoryTableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要查看的课程.
        /// </summary>
        public static string Settings_SelectSubjectDesc {
            get {
                return ResourceManager.GetString("Settings_SelectSubjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否在表格中显示权重.
        /// </summary>
        public static string Settings_ShowWeightDesc {
            get {
                return ResourceManager.GetString("Settings_ShowWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择历史记录的查看方式.
        /// </summary>
        public static string Settings_ViewModeDesc {
            get {
                return ResourceManager.GetString("Settings_ViewModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示权重.
        /// </summary>
        public static string ShowWeight {
            get {
                return ResourceManager.GetString("ShowWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按时间查看.
        /// </summary>
        public static string ViewByTime {
            get {
                return ResourceManager.GetString("ViewByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看历史记录.
        /// </summary>
        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开历史记录表格查看详细数据.
        /// </summary>
        public static string ViewHistoryDesc {
            get {
                return ResourceManager.GetString("ViewHistoryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看模式.
        /// </summary>
        public static string ViewMode {
            get {
                return ResourceManager.GetString("ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中奖次数.
        /// </summary>
        public static string WinningTimes {
            get {
                return ResourceManager.GetString("WinningTimes", resourceCulture);
            }
        }
    }
}
