//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.AboutPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.AboutPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Bilibili {
            get {
                return ResourceManager.GetString("Bilibili", resourceCulture);
            }
        }
        
        public static string BilibiliDesc {
            get {
                return ResourceManager.GetString("BilibiliDesc", resourceCulture);
            }
        }
        
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        public static string CheckUpdateDesc {
            get {
                return ResourceManager.GetString("CheckUpdateDesc", resourceCulture);
            }
        }
        
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        public static string ContributorsDesc {
            get {
                return ResourceManager.GetString("ContributorsDesc", resourceCulture);
            }
        }
        
        public static string ContributorsRole1 {
            get {
                return ResourceManager.GetString("ContributorsRole1", resourceCulture);
            }
        }
        
        public static string ContributorsRole10 {
            get {
                return ResourceManager.GetString("ContributorsRole10", resourceCulture);
            }
        }
        
        public static string ContributorsRole11 {
            get {
                return ResourceManager.GetString("ContributorsRole11", resourceCulture);
            }
        }
        
        public static string ContributorsRole2 {
            get {
                return ResourceManager.GetString("ContributorsRole2", resourceCulture);
            }
        }
        
        public static string ContributorsRole3 {
            get {
                return ResourceManager.GetString("ContributorsRole3", resourceCulture);
            }
        }
        
        public static string ContributorsRole4 {
            get {
                return ResourceManager.GetString("ContributorsRole4", resourceCulture);
            }
        }
        
        public static string ContributorsRole5 {
            get {
                return ResourceManager.GetString("ContributorsRole5", resourceCulture);
            }
        }
        
        public static string ContributorsRole6 {
            get {
                return ResourceManager.GetString("ContributorsRole6", resourceCulture);
            }
        }
        
        public static string ContributorsRole7 {
            get {
                return ResourceManager.GetString("ContributorsRole7", resourceCulture);
            }
        }
        
        public static string CopyUserInfo {
            get {
                return ResourceManager.GetString("CopyUserInfo", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string CopyrightDesc {
            get {
                return ResourceManager.GetString("CopyrightDesc", resourceCulture);
            }
        }
        
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        public static string DonationDesc {
            get {
                return ResourceManager.GetString("DonationDesc", resourceCulture);
            }
        }
        
        public static string FirstUseTime {
            get {
                return ResourceManager.GetString("FirstUseTime", resourceCulture);
            }
        }
        
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        public static string GitHubDesc {
            get {
                return ResourceManager.GetString("GitHubDesc", resourceCulture);
            }
        }
        
        public static string LotteryTotalCount {
            get {
                return ResourceManager.GetString("LotteryTotalCount", resourceCulture);
            }
        }
        
        public static string OrganizationWebsite {
            get {
                return ResourceManager.GetString("OrganizationWebsite", resourceCulture);
            }
        }
        
        public static string OrganizationWebsiteDesc {
            get {
                return ResourceManager.GetString("OrganizationWebsiteDesc", resourceCulture);
            }
        }
        
        public static string RollCallTotalCount {
            get {
                return ResourceManager.GetString("RollCallTotalCount", resourceCulture);
            }
        }
        
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        public static string RuntimeDays {
            get {
                return ResourceManager.GetString("RuntimeDays", resourceCulture);
            }
        }
        
        public static string RuntimeHms {
            get {
                return ResourceManager.GetString("RuntimeHms", resourceCulture);
            }
        }
        
        public static string RuntimeYears {
            get {
                return ResourceManager.GetString("RuntimeYears", resourceCulture);
            }
        }
        
        public static string TotalDrawCount {
            get {
                return ResourceManager.GetString("TotalDrawCount", resourceCulture);
            }
        }
        
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        public static string UpdateChannelBeta {
            get {
                return ResourceManager.GetString("UpdateChannelBeta", resourceCulture);
            }
        }
        
        public static string UpdateChannelDesc {
            get {
                return ResourceManager.GetString("UpdateChannelDesc", resourceCulture);
            }
        }
        
        public static string UpdateChannelOfficial {
            get {
                return ResourceManager.GetString("UpdateChannelOfficial", resourceCulture);
            }
        }
        
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        public static string UserIdDesc {
            get {
                return ResourceManager.GetString("UserIdDesc", resourceCulture);
            }
        }
        
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        public static string UserInfoDesc {
            get {
                return ResourceManager.GetString("UserInfoDesc", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string VersionDesc {
            get {
                return ResourceManager.GetString("VersionDesc", resourceCulture);
            }
        }
        
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        public static string WebsiteDesc {
            get {
                return ResourceManager.GetString("WebsiteDesc", resourceCulture);
            }
        }
    }
}
