//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.AboutPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.AboutPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string Bilibili {
            get {
                return ResourceManager.GetString("Bilibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贡献人员.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设计、创意、策划、维护、文档、测试.
        /// </summary>
        public static string ContributorsRole1 {
            get {
                return ResourceManager.GetString("ContributorsRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIsland 插件、ClassIsland 联动.
        /// </summary>
        public static string ContributorsRole10 {
            get {
                return ResourceManager.GetString("ContributorsRole10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string ContributorsRole11 {
            get {
                return ResourceManager.GetString("ContributorsRole11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性能.
        /// </summary>
        public static string ContributorsRole2 {
            get {
                return ResourceManager.GetString("ContributorsRole2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应式前端页面设计及维护、文档.
        /// </summary>
        public static string ContributorsRole3 {
            get {
                return ResourceManager.GetString("ContributorsRole3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创意、文档.
        /// </summary>
        public static string ContributorsRole4 {
            get {
                return ResourceManager.GetString("ContributorsRole4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创意.
        /// </summary>
        public static string ContributorsRole5 {
            get {
                return ResourceManager.GetString("ContributorsRole5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装包制作.
        /// </summary>
        public static string ContributorsRole6 {
            get {
                return ResourceManager.GetString("ContributorsRole6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 响应式前端页面设计及维护、文档.
        /// </summary>
        public static string ContributorsRole7 {
            get {
                return ResourceManager.GetString("ContributorsRole7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制用户信息.
        /// </summary>
        public static string CopyUserInfo {
            get {
                return ResourceManager.GetString("CopyUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捐赠支持.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首次使用时间.
        /// </summary>
        public static string FirstUseTime {
            get {
                return ResourceManager.GetString("FirstUseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖总次数.
        /// </summary>
        public static string LotteryTotalCount {
            get {
                return ResourceManager.GetString("LotteryTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string OrganizationWebsite {
            get {
                return ResourceManager.GetString("OrganizationWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名总次数.
        /// </summary>
        public static string RollCallTotalCount {
            get {
                return ResourceManager.GetString("RollCallTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件运行时长.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}天.
        /// </summary>
        public static string RuntimeDays {
            get {
                return ResourceManager.GetString("RuntimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}:{1:00}:{2:00}.
        /// </summary>
        public static string RuntimeHms {
            get {
                return ResourceManager.GetString("RuntimeHms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}年.
        /// </summary>
        public static string RuntimeYears {
            get {
                return ResourceManager.GetString("RuntimeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问黎泽懿_Aionflux的Bilibili账号.
        /// </summary>
        public static string Settings_BilibiliDesc {
            get {
                return ResourceManager.GetString("Settings_BilibiliDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string Settings_CheckUpdateDesc {
            get {
                return ResourceManager.GetString("Settings_CheckUpdateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击查看详细贡献者信息.
        /// </summary>
        public static string Settings_ContributorsDesc {
            get {
                return ResourceManager.GetString("Settings_ContributorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecRandom遵循GPL-3.0协议.
        /// </summary>
        public static string Settings_CopyrightDesc {
            get {
                return ResourceManager.GetString("Settings_CopyrightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持项目发展，感谢您的捐赠.
        /// </summary>
        public static string Settings_DonationDesc {
            get {
                return ResourceManager.GetString("Settings_DonationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问项目代码仓库.
        /// </summary>
        public static string Settings_GitHubDesc {
            get {
                return ResourceManager.GetString("Settings_GitHubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问 SECTL 组织官网.
        /// </summary>
        public static string Settings_OrganizationWebsiteDesc {
            get {
                return ResourceManager.GetString("Settings_OrganizationWebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择SecRandom软件更新频道.
        /// </summary>
        public static string Settings_UpdateChannelDesc {
            get {
                return ResourceManager.GetString("Settings_UpdateChannelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示当前软件版本号.
        /// </summary>
        public static string Settings_VersionDesc {
            get {
                return ResourceManager.GetString("Settings_VersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问SecRandom软件官网.
        /// </summary>
        public static string Settings_WebsiteDesc {
            get {
                return ResourceManager.GetString("Settings_WebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件总抽取次数.
        /// </summary>
        public static string TotalDrawCount {
            get {
                return ResourceManager.GetString("TotalDrawCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新频道.
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试版.
        /// </summary>
        public static string UpdateChannelBeta {
            get {
                return ResourceManager.GetString("UpdateChannelBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正式版.
        /// </summary>
        public static string UpdateChannelOfficial {
            get {
                return ResourceManager.GetString("UpdateChannelOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于错误追踪的离线唯一标识.
        /// </summary>
        public static string UserIdDesc {
            get {
                return ResourceManager.GetString("UserIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户信息.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示本机与使用信息.
        /// </summary>
        public static string UserInfoDesc {
            get {
                return ResourceManager.GetString("UserInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前电脑用户名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
