//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ThemeManagementPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ThemeManagementPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        public static string BackgroundColorSolid {
            get {
                return ResourceManager.GetString("BackgroundColorSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string BackgroundDefault {
            get {
                return ResourceManager.GetString("BackgroundDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景图片.
        /// </summary>
        public static string BackgroundImageFile {
            get {
                return ResourceManager.GetString("BackgroundImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景类型.
        /// </summary>
        public static string BackgroundType {
            get {
                return ResourceManager.GetString("BackgroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片亮度.
        /// </summary>
        public static string ImageBrightness {
            get {
                return ResourceManager.GetString("ImageBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗口背景.
        /// </summary>
        public static string MainWindowBackground {
            get {
                return ResourceManager.GetString("MainWindowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内置通知浮窗背景.
        /// </summary>
        public static string NotificationFloatingWindowBackground {
            get {
                return ResourceManager.GetString("NotificationFloatingWindowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置背景颜色.
        /// </summary>
        public static string Settings_BackgroundColorSolidDesc {
            get {
                return ResourceManager.GetString("Settings_BackgroundColorSolidDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择背景图片文件.
        /// </summary>
        public static string Settings_BackgroundImageFileDesc {
            get {
                return ResourceManager.GetString("Settings_BackgroundImageFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择背景类型.
        /// </summary>
        public static string Settings_BackgroundTypeDesc {
            get {
                return ResourceManager.GetString("Settings_BackgroundTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整背景图片亮度.
        /// </summary>
        public static string Settings_ImageBrightnessDesc {
            get {
                return ResourceManager.GetString("Settings_ImageBrightnessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Settings_SelectImage {
            get {
                return ResourceManager.GetString("Settings_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口背景.
        /// </summary>
        public static string SettingsWindowBackground {
            get {
                return ResourceManager.GetString("SettingsWindowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string ThemeManagement {
            get {
                return ResourceManager.GetString("ThemeManagement", resourceCulture);
            }
        }
    }
}
