//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ThemeManagementPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ThemeManagementPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ThemeManagement {
            get {
                return ResourceManager.GetString("ThemeManagement", resourceCulture);
            }
        }
        
        public static string ThemeManagementDesc {
            get {
                return ResourceManager.GetString("ThemeManagementDesc", resourceCulture);
            }
        }
        
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        public static string RefreshMarket {
            get {
                return ResourceManager.GetString("RefreshMarket", resourceCulture);
            }
        }
        
        public static string ReloadThemes {
            get {
                return ResourceManager.GetString("ReloadThemes", resourceCulture);
            }
        }
        
        public static string OpenThemeFolder {
            get {
                return ResourceManager.GetString("OpenThemeFolder", resourceCulture);
            }
        }
        
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        public static string NoThemesInstalled {
            get {
                return ResourceManager.GetString("NoThemesInstalled", resourceCulture);
            }
        }
        
        public static string NoThemesInstalledDesc {
            get {
                return ResourceManager.GetString("NoThemesInstalledDesc", resourceCulture);
            }
        }
        
        public static string NoThemesMarket {
            get {
                return ResourceManager.GetString("NoThemesMarket", resourceCulture);
            }
        }
        
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string MainWindowBackground {
            get {
                return ResourceManager.GetString("MainWindowBackground", resourceCulture);
            }
        }
        
        public static string MainWindowBackgroundDesc {
            get {
                return ResourceManager.GetString("MainWindowBackgroundDesc", resourceCulture);
            }
        }
        
        public static string SettingsWindowBackground {
            get {
                return ResourceManager.GetString("SettingsWindowBackground", resourceCulture);
            }
        }
        
        public static string NotificationFloatingWindowBackground {
            get {
                return ResourceManager.GetString("NotificationFloatingWindowBackground", resourceCulture);
            }
        }
        
        public static string BackgroundType {
            get {
                return ResourceManager.GetString("BackgroundType", resourceCulture);
            }
        }
        
        public static string BackgroundTypeDesc {
            get {
                return ResourceManager.GetString("BackgroundTypeDesc", resourceCulture);
            }
        }
        
        public static string BackgroundDefault {
            get {
                return ResourceManager.GetString("BackgroundDefault", resourceCulture);
            }
        }
        
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        public static string BackgroundGradient {
            get {
                return ResourceManager.GetString("BackgroundGradient", resourceCulture);
            }
        }
        
        public static string BackgroundColorSolid {
            get {
                return ResourceManager.GetString("BackgroundColorSolid", resourceCulture);
            }
        }
        
        public static string BackgroundColorSolidDesc {
            get {
                return ResourceManager.GetString("BackgroundColorSolidDesc", resourceCulture);
            }
        }
        
        public static string GradientStartColor {
            get {
                return ResourceManager.GetString("GradientStartColor", resourceCulture);
            }
        }
        
        public static string GradientEndColor {
            get {
                return ResourceManager.GetString("GradientEndColor", resourceCulture);
            }
        }
        
        public static string GradientDirection {
            get {
                return ResourceManager.GetString("GradientDirection", resourceCulture);
            }
        }
        
        public static string GradientTopToBottom {
            get {
                return ResourceManager.GetString("GradientTopToBottom", resourceCulture);
            }
        }
        
        public static string GradientBottomToTop {
            get {
                return ResourceManager.GetString("GradientBottomToTop", resourceCulture);
            }
        }
        
        public static string GradientLeftToRight {
            get {
                return ResourceManager.GetString("GradientLeftToRight", resourceCulture);
            }
        }
        
        public static string GradientRightToLeft {
            get {
                return ResourceManager.GetString("GradientRightToLeft", resourceCulture);
            }
        }
        
        public static string BackgroundImageFile {
            get {
                return ResourceManager.GetString("BackgroundImageFile", resourceCulture);
            }
        }
        
        public static string BackgroundImageFileDesc {
            get {
                return ResourceManager.GetString("BackgroundImageFileDesc", resourceCulture);
            }
        }
        
        public static string ImageBrightness {
            get {
                return ResourceManager.GetString("ImageBrightness", resourceCulture);
            }
        }
        
        public static string ImageBrightnessDesc {
            get {
                return ResourceManager.GetString("ImageBrightnessDesc", resourceCulture);
            }
        }
        
        public static string BackgroundBlur {
            get {
                return ResourceManager.GetString("BackgroundBlur", resourceCulture);
            }
        }
        
        public static string BackgroundBlurDesc {
            get {
                return ResourceManager.GetString("BackgroundBlurDesc", resourceCulture);
            }
        }
        
        public static string BlurEnable {
            get {
                return ResourceManager.GetString("BlurEnable", resourceCulture);
            }
        }
        
        public static string BlurDisable {
            get {
                return ResourceManager.GetString("BlurDisable", resourceCulture);
            }
        }
        
        public static string BlurRadius {
            get {
                return ResourceManager.GetString("BlurRadius", resourceCulture);
            }
        }
        
        public static string BackgroundPreview {
            get {
                return ResourceManager.GetString("BackgroundPreview", resourceCulture);
            }
        }
        
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        public static string ClearImage {
            get {
                return ResourceManager.GetString("ClearImage", resourceCulture);
            }
        }
        
        public static string PreviewDefault {
            get {
                return ResourceManager.GetString("PreviewDefault", resourceCulture);
            }
        }
        
        public static string PreviewNoImage {
            get {
                return ResourceManager.GetString("PreviewNoImage", resourceCulture);
            }
        }
        
        public static string ApplyToRollCall {
            get {
                return ResourceManager.GetString("ApplyToRollCall", resourceCulture);
            }
        }
        
        public static string ApplyToLottery {
            get {
                return ResourceManager.GetString("ApplyToLottery", resourceCulture);
            }
        }
        
        public static string CancelRollCall {
            get {
                return ResourceManager.GetString("CancelRollCall", resourceCulture);
            }
        }
        
        public static string CancelLottery {
            get {
                return ResourceManager.GetString("CancelLottery", resourceCulture);
            }
        }
    }
}
