//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.SecuritySettingsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.SecuritySettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础安全设置.
        /// </summary>
        public static string BasicSafetySettings {
            get {
                return ResourceManager.GetString("BasicSafetySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定U盘.
        /// </summary>
        public static string BindUsb {
            get {
                return ResourceManager.GetString("BindUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先绑定U盘.
        /// </summary>
        public static string ErrorBindUsbFirst {
            get {
                return ResourceManager.GetString("ErrorBindUsbFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先设置密码.
        /// </summary>
        public static string ErrorSetPasswordFirst {
            get {
                return ResourceManager.GetString("ErrorSetPasswordFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先设置TOTP.
        /// </summary>
        public static string ErrorSetTotpFirst {
            get {
                return ResourceManager.GetString("ErrorSetTotpFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出验证.
        /// </summary>
        public static string ExitSwitch {
            get {
                return ResourceManager.GetString("ExitSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能正在开发中.
        /// </summary>
        public static string FeatureInDevelopment {
            get {
                return ResourceManager.GetString("FeatureInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开设置验证.
        /// </summary>
        public static string OpenSettingsSwitch {
            get {
                return ResourceManager.GetString("OpenSettingsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置预览开关.
        /// </summary>
        public static string PreviewSettingsSwitch {
            get {
                return ResourceManager.GetString("PreviewSettingsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启验证.
        /// </summary>
        public static string RestartSwitch {
            get {
                return ResourceManager.GetString("RestartSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全开关.
        /// </summary>
        public static string SafetySwitch {
            get {
                return ResourceManager.GetString("SafetySwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全操作.
        /// </summary>
        public static string SecurityOperations {
            get {
                return ResourceManager.GetString("SecurityOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置/修改密码.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定用于验证的U盘设备.
        /// </summary>
        public static string Settings_BindUsbDesc {
            get {
                return ResourceManager.GetString("Settings_BindUsbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后退出软件时需要安全验证.
        /// </summary>
        public static string Settings_ExitSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_ExitSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后打开设置窗口时需要安全验证.
        /// </summary>
        public static string Settings_OpenSettingsSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_OpenSettingsSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入设置的验证时允许预览设置.
        /// </summary>
        public static string Settings_PreviewSettingsSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_PreviewSettingsSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后重启软件时需要安全验证.
        /// </summary>
        public static string Settings_RestartSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_RestartSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后所有安全操作都需要验证密码.
        /// </summary>
        public static string Settings_SafetySwitchDesc {
            get {
                return ResourceManager.GetString("Settings_SafetySwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置需要安全验证的操作.
        /// </summary>
        public static string Settings_SecurityOperationsDesc {
            get {
                return ResourceManager.GetString("Settings_SecurityOperationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置或修改安全验证密码.
        /// </summary>
        public static string Settings_SetPasswordDesc {
            get {
                return ResourceManager.GetString("Settings_SetPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置TOTP动态口令验证.
        /// </summary>
        public static string Settings_SetTotpDesc {
            get {
                return ResourceManager.GetString("Settings_SetTotpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后显示或隐藏浮窗时需要安全验证.
        /// </summary>
        public static string Settings_ShowHideFloatingWindowSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_ShowHideFloatingWindowSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后可在安全操作中使用TOTP动态口令.
        /// </summary>
        public static string Settings_TotpSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_TotpSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解除U盘设备绑定.
        /// </summary>
        public static string Settings_UnbindUsbDesc {
            get {
                return ResourceManager.GetString("Settings_UnbindUsbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用后可在安全操作中使用U盘验证.
        /// </summary>
        public static string Settings_UsbSwitchDesc {
            get {
                return ResourceManager.GetString("Settings_UsbSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置安全功能验证方式.
        /// </summary>
        public static string Settings_VerificationMethodDesc {
            get {
                return ResourceManager.GetString("Settings_VerificationMethodDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择安全验证组合方式.
        /// </summary>
        public static string Settings_VerificationProcessDesc {
            get {
                return ResourceManager.GetString("Settings_VerificationProcessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置TOTP.
        /// </summary>
        public static string SetTotp {
            get {
                return ResourceManager.GetString("SetTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示/隐藏浮窗验证.
        /// </summary>
        public static string ShowHideFloatingWindowSwitch {
            get {
                return ResourceManager.GetString("ShowHideFloatingWindowSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP验证.
        /// </summary>
        public static string TotpSwitch {
            get {
                return ResourceManager.GetString("TotpSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解绑U盘.
        /// </summary>
        public static string UnbindUsb {
            get {
                return ResourceManager.GetString("UnbindUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U盘验证.
        /// </summary>
        public static string UsbSwitch {
            get {
                return ResourceManager.GetString("UsbSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证方式.
        /// </summary>
        public static string VerificationMethod {
            get {
                return ResourceManager.GetString("VerificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全验证步骤.
        /// </summary>
        public static string VerificationProcess {
            get {
                return ResourceManager.GetString("VerificationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单步验证（任选一种方式）.
        /// </summary>
        public static string VerificationProcessOneStep {
            get {
                return ResourceManager.GetString("VerificationProcessOneStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅密码.
        /// </summary>
        public static string VerificationProcessPasswordOnly {
            get {
                return ResourceManager.GetString("VerificationProcessPasswordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码+TOTP.
        /// </summary>
        public static string VerificationProcessPasswordTotp {
            get {
                return ResourceManager.GetString("VerificationProcessPasswordTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码+TOTP+U盘解锁.
        /// </summary>
        public static string VerificationProcessPasswordTotpUsb {
            get {
                return ResourceManager.GetString("VerificationProcessPasswordTotpUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码+U盘解锁.
        /// </summary>
        public static string VerificationProcessPasswordUsb {
            get {
                return ResourceManager.GetString("VerificationProcessPasswordUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅TOTP.
        /// </summary>
        public static string VerificationProcessTotpOnly {
            get {
                return ResourceManager.GetString("VerificationProcessTotpOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP+U盘解锁.
        /// </summary>
        public static string VerificationProcessTotpUsb {
            get {
                return ResourceManager.GetString("VerificationProcessTotpUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅U盘解锁.
        /// </summary>
        public static string VerificationProcessUsbOnly {
            get {
                return ResourceManager.GetString("VerificationProcessUsbOnly", resourceCulture);
            }
        }
    }
}
