//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.DrawSettingsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.DrawSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画模式.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动播放动画.
        /// </summary>
        public static string AnimationAuto {
            get {
                return ResourceManager.GetString("AnimationAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画/结果颜色主题.
        /// </summary>
        public static string AnimationColorTheme {
            get {
                return ResourceManager.GetString("AnimationColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定颜色.
        /// </summary>
        public static string AnimationColorThemeFixed {
            get {
                return ResourceManager.GetString("AnimationColorThemeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string AnimationColorThemeOff {
            get {
                return ResourceManager.GetString("AnimationColorThemeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机颜色.
        /// </summary>
        public static string AnimationColorThemeRandom {
            get {
                return ResourceManager.GetString("AnimationColorThemeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置动画效果.
        /// </summary>
        public static string AnimationDesc {
            get {
                return ResourceManager.GetString("AnimationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直接显示结果.
        /// </summary>
        public static string AnimationDirect {
            get {
                return ResourceManager.GetString("AnimationDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画/结果固定颜色.
        /// </summary>
        public static string AnimationFixedColor {
            get {
                return ResourceManager.GetString("AnimationFixedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画间隔.
        /// </summary>
        public static string AnimationInterval {
            get {
                return ResourceManager.GetString("AnimationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动停止动画.
        /// </summary>
        public static string AnimationManual {
            get {
                return ResourceManager.GetString("AnimationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动播放次数.
        /// </summary>
        public static string AutoplayCount {
            get {
                return ResourceManager.GetString("AutoplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摄像头显示分辨率.
        /// </summary>
        public static string CameraDisplayResolution {
            get {
                return ResourceManager.GetString("CameraDisplayResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动（{0}）.
        /// </summary>
        public static string CameraDisplayResolutionAutoFormat {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionAutoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string CameraDisplayResolutionPlaceholder {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        public static string CameraDisplayResolutionUnknown {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模式.
        /// </summary>
        public static string CameraPreviewMode {
            get {
                return ResourceManager.GetString("CameraPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取模式.
        /// </summary>
        public static string CameraPreviewModePicking {
            get {
                return ResourceManager.GetString("CameraPreviewModePicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别模式.
        /// </summary>
        public static string CameraPreviewModeRecognition {
            get {
                return ResourceManager.GetString("CameraPreviewModeRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摄像头.
        /// </summary>
        public static string CameraSource {
            get {
                return ResourceManager.GetString("CameraSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除抽取记录方式.
        /// </summary>
        public static string ClearRecord {
            get {
                return ResourceManager.GetString("ClearRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直到全部抽取完.
        /// </summary>
        public static string ClearRecordAll {
            get {
                return ResourceManager.GetString("ClearRecordAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启后清除.
        /// </summary>
        public static string ClearRecordRestart {
            get {
                return ResourceManager.GetString("ClearRecordRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义字体.
        /// </summary>
        public static string CustomFont {
            get {
                return ResourceManager.GetString("CustomFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认抽取名单.
        /// </summary>
        public static string DefaultClass {
            get {
                return ResourceManager.GetString("DefaultClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择名单.
        /// </summary>
        public static string DefaultClassPlaceholder {
            get {
                return ResourceManager.GetString("DefaultClassPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认抽取奖池.
        /// </summary>
        public static string DefaultPool {
            get {
                return ResourceManager.GetString("DefaultPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string DefaultPoolPlaceholder {
            get {
                return ResourceManager.GetString("DefaultPoolPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别模型.
        /// </summary>
        public static string DetectorType {
            get {
                return ResourceManager.GetString("DetectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version-RFB-640.onnx.
        /// </summary>
        public static string DetectorTypePlaceholder {
            get {
                return ResourceManager.GetString("DetectorTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击后禁用时间.
        /// </summary>
        public static string DisableAfterClick {
            get {
                return ResourceManager.GetString("DisableAfterClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果显示格式.
        /// </summary>
        public static string DisplayFormat {
            get {
                return ResourceManager.GetString("DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号.
        /// </summary>
        public static string DisplayFormatId {
            get {
                return ResourceManager.GetString("DisplayFormatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学号+姓名.
        /// </summary>
        public static string DisplayFormatIdName {
            get {
                return ResourceManager.GetString("DisplayFormatIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string DisplayFormatName {
            get {
                return ResourceManager.GetString("DisplayFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果显示样式.
        /// </summary>
        public static string DisplayStyle {
            get {
                return ResourceManager.GetString("DisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片样式.
        /// </summary>
        public static string DisplayStyleCard {
            get {
                return ResourceManager.GetString("DisplayStyleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认样式.
        /// </summary>
        public static string DisplayStyleDefault {
            get {
                return ResourceManager.GetString("DisplayStyleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取人数.
        /// </summary>
        public static string DrawCount {
            get {
                return ResourceManager.GetString("DrawCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取模式.
        /// </summary>
        public static string DrawMode {
            get {
                return ResourceManager.GetString("DrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不重复抽取.
        /// </summary>
        public static string DrawModeNoRepeat {
            get {
                return ResourceManager.GetString("DrawModeNoRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复抽取.
        /// </summary>
        public static string DrawModeRepeat {
            get {
                return ResourceManager.GetString("DrawModeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半重复抽取.
        /// </summary>
        public static string DrawModeSemiRepeat {
            get {
                return ResourceManager.GetString("DrawModeSemiRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在左侧导航栏选择具体设置.
        /// </summary>
        public static string DrawSettingsNavHint {
            get {
                return ResourceManager.GetString("DrawSettingsNavHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取方式.
        /// </summary>
        public static string DrawType {
            get {
                return ResourceManager.GetString("DrawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公平抽取.
        /// </summary>
        public static string DrawTypeFair {
            get {
                return ResourceManager.GetString("DrawTypeFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机抽取.
        /// </summary>
        public static string DrawTypeRandom {
            get {
                return ResourceManager.GetString("DrawTypeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string FaceDetectorAdvancedSettings {
            get {
                return ResourceManager.GetString("FaceDetectorAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取功能.
        /// </summary>
        public static string FaceDetectorExtractionFunction {
            get {
                return ResourceManager.GetString("FaceDetectorExtractionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取动画.
        /// </summary>
        public static string FaceDetectorPickerAnimationSettings {
            get {
                return ResourceManager.GetString("FaceDetectorPickerAnimationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸抽取设置.
        /// </summary>
        public static string FaceDetectorSettings {
            get {
                return ResourceManager.GetString("FaceDetectorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半重复抽取次数.
        /// </summary>
        public static string HalfRepeat {
            get {
                return ResourceManager.GetString("HalfRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 独立名单配置.
        /// </summary>
        public static string ListSpecificSettings {
            get {
                return ResourceManager.GetString("ListSpecificSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择班级.
        /// </summary>
        public static string ListSpecificSettingsSelectClass {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择名单.
        /// </summary>
        public static string ListSpecificSettingsSelectList {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string ListSpecificSettingsSelectPool {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步到全局.
        /// </summary>
        public static string ListSpecificSettingsSync {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用全局设置.
        /// </summary>
        public static string ListSpecificSettingsSyncButton {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画设置.
        /// </summary>
        public static string LotteryAnimationSettings {
            get {
                return ResourceManager.GetString("LotteryAnimationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题设置.
        /// </summary>
        public static string LotteryColorThemeSettings {
            get {
                return ResourceManager.GetString("LotteryColorThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string LotteryDisplaySettings {
            get {
                return ResourceManager.GetString("LotteryDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取功能.
        /// </summary>
        public static string LotteryExtractionFunction {
            get {
                return ResourceManager.GetString("LotteryExtractionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示奖品图片.
        /// </summary>
        public static string LotteryImage {
            get {
                return ResourceManager.GetString("LotteryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片文件夹.
        /// </summary>
        public static string LotteryImageFolder {
            get {
                return ResourceManager.GetString("LotteryImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string LotteryImageFolderButton {
            get {
                return ResourceManager.GetString("LotteryImageFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片位置.
        /// </summary>
        public static string LotteryImagePosition {
            get {
                return ResourceManager.GetString("LotteryImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部.
        /// </summary>
        public static string LotteryImagePositionBottom {
            get {
                return ResourceManager.GetString("LotteryImagePositionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左部.
        /// </summary>
        public static string LotteryImagePositionLeft {
            get {
                return ResourceManager.GetString("LotteryImagePositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右部.
        /// </summary>
        public static string LotteryImagePositionRight {
            get {
                return ResourceManager.GetString("LotteryImagePositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部.
        /// </summary>
        public static string LotteryImagePositionTop {
            get {
                return ResourceManager.GetString("LotteryImagePositionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片设置.
        /// </summary>
        public static string LotteryImageSettings {
            get {
                return ResourceManager.GetString("LotteryImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖设置.
        /// </summary>
        public static string LotterySettings {
            get {
                return ResourceManager.GetString("LotterySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型输入尺寸.
        /// </summary>
        public static string ModelInputSize {
            get {
                return ResourceManager.GetString("ModelInputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模型文件夹.
        /// </summary>
        public static string OpenModelFolder {
            get {
                return ResourceManager.GetString("OpenModelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string OpenModelFolderButton {
            get {
                return ResourceManager.GetString("OpenModelFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框颜色.
        /// </summary>
        public static string PickerFrameColor {
            get {
                return ResourceManager.GetString("PickerFrameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取时长.
        /// </summary>
        public static string PickingDurationSeconds {
            get {
                return ResourceManager.GetString("PickingDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过程音效.
        /// </summary>
        public static string PlayProcessAudio {
            get {
                return ResourceManager.GetString("PlayProcessAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果音效.
        /// </summary>
        public static string PlayResultAudio {
            get {
                return ResourceManager.GetString("PlayResultAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画设置.
        /// </summary>
        public static string QuickDrawAnimationSettings {
            get {
                return ResourceManager.GetString("QuickDrawAnimationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题设置.
        /// </summary>
        public static string QuickDrawColorThemeSettings {
            get {
                return ResourceManager.GetString("QuickDrawColorThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string QuickDrawDisplaySettings {
            get {
                return ResourceManager.GetString("QuickDrawDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取功能.
        /// </summary>
        public static string QuickDrawExtractionFunction {
            get {
                return ResourceManager.GetString("QuickDrawExtractionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽设置.
        /// </summary>
        public static string QuickDrawSettings {
            get {
                return ResourceManager.GetString("QuickDrawSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果布局动画时长.
        /// </summary>
        public static string ResultFlowAnimationDuration {
            get {
                return ResourceManager.GetString("ResultFlowAnimationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果布局动画.
        /// </summary>
        public static string ResultFlowAnimationStyle {
            get {
                return ResourceManager.GetString("ResultFlowAnimationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画设置.
        /// </summary>
        public static string RollCallAnimationSettings {
            get {
                return ResourceManager.GetString("RollCallAnimationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题设置.
        /// </summary>
        public static string RollCallColorThemeSettings {
            get {
                return ResourceManager.GetString("RollCallColorThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string RollCallDisplaySettings {
            get {
                return ResourceManager.GetString("RollCallDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取功能.
        /// </summary>
        public static string RollCallExtractionFunction {
            get {
                return ResourceManager.GetString("RollCallExtractionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名设置.
        /// </summary>
        public static string RollCallSettings {
            get {
                return ResourceManager.GetString("RollCallSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生头像设置.
        /// </summary>
        public static string RollCallStudentImageSettings {
            get {
                return ResourceManager.GetString("RollCallStudentImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置动画/结果颜色主题.
        /// </summary>
        public static string Settings_AnimationColorThemeDesc {
            get {
                return ResourceManager.GetString("Settings_AnimationColorThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置动画/结果固定颜色.
        /// </summary>
        public static string Settings_AnimationFixedColorDesc {
            get {
                return ResourceManager.GetString("Settings_AnimationFixedColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置动画间隔时间（毫秒）.
        /// </summary>
        public static string Settings_AnimationIntervalDesc {
            get {
                return ResourceManager.GetString("Settings_AnimationIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置动画自动播放次数.
        /// </summary>
        public static string Settings_AutoplayCountDesc {
            get {
                return ResourceManager.GetString("Settings_AutoplayCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动使用最高分辨率.
        /// </summary>
        public static string Settings_CameraDisplayResolutionDesc {
            get {
                return ResourceManager.GetString("Settings_CameraDisplayResolutionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择摄像头预览工作模式.
        /// </summary>
        public static string Settings_CameraPreviewModeDesc {
            get {
                return ResourceManager.GetString("Settings_CameraPreviewModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择人脸抽取使用的摄像头设备.
        /// </summary>
        public static string Settings_CameraSourceDesc {
            get {
                return ResourceManager.GetString("Settings_CameraSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置清除抽取记录的时机.
        /// </summary>
        public static string Settings_ClearRecordDesc {
            get {
                return ResourceManager.GetString("Settings_ClearRecordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择自定义字体.
        /// </summary>
        public static string Settings_CustomFontDesc {
            get {
                return ResourceManager.GetString("Settings_CustomFontDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置默认抽取名单.
        /// </summary>
        public static string Settings_DefaultClassDesc {
            get {
                return ResourceManager.GetString("Settings_DefaultClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置默认抽取奖池.
        /// </summary>
        public static string Settings_DefaultPoolDesc {
            get {
                return ResourceManager.GetString("Settings_DefaultPoolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置人脸识别模型文件.
        /// </summary>
        public static string Settings_DetectorTypeDesc {
            get {
                return ResourceManager.GetString("Settings_DetectorTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点击后禁用按钮的时间（秒）.
        /// </summary>
        public static string Settings_DisableAfterClickDesc {
            get {
                return ResourceManager.GetString("Settings_DisableAfterClickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置结果显示格式.
        /// </summary>
        public static string Settings_DisplayFormatDesc {
            get {
                return ResourceManager.GetString("Settings_DisplayFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置结果显示样式.
        /// </summary>
        public static string Settings_DisplayStyleDesc {
            get {
                return ResourceManager.GetString("Settings_DisplayStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置每次抽取的人数.
        /// </summary>
        public static string Settings_DrawCountDesc {
            get {
                return ResourceManager.GetString("Settings_DrawCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取模式.
        /// </summary>
        public static string Settings_DrawModeDesc {
            get {
                return ResourceManager.GetString("Settings_DrawModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取方式.
        /// </summary>
        public static string Settings_DrawTypeDesc {
            get {
                return ResourceManager.GetString("Settings_DrawTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置字体大小.
        /// </summary>
        public static string Settings_FontSizeDesc {
            get {
                return ResourceManager.GetString("Settings_FontSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置每人被抽中多少次后清除抽取记录.
        /// </summary>
        public static string Settings_HalfRepeatDesc {
            get {
                return ResourceManager.GetString("Settings_HalfRepeatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为所选班级设置独立参数.
        /// </summary>
        public static string Settings_ListSpecificSettingsSelectClassDesc {
            get {
                return ResourceManager.GetString("Settings_ListSpecificSettingsSelectClassDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为所选名单设置独立参数.
        /// </summary>
        public static string Settings_ListSpecificSettingsSelectListDesc {
            get {
                return ResourceManager.GetString("Settings_ListSpecificSettingsSelectListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 为所选奖池设置独立参数.
        /// </summary>
        public static string Settings_ListSpecificSettingsSelectPoolDesc {
            get {
                return ResourceManager.GetString("Settings_ListSpecificSettingsSelectPoolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除独立配置，使用全局设置.
        /// </summary>
        public static string Settings_ListSpecificSettingsSyncDesc {
            get {
                return ResourceManager.GetString("Settings_ListSpecificSettingsSyncDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置是否显示奖品图片.
        /// </summary>
        public static string Settings_LotteryImageDesc {
            get {
                return ResourceManager.GetString("Settings_LotteryImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理奖品图片文件.
        /// </summary>
        public static string Settings_LotteryImageFolderDesc {
            get {
                return ResourceManager.GetString("Settings_LotteryImageFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品图片在结果中的位置.
        /// </summary>
        public static string Settings_LotteryImagePositionDesc {
            get {
                return ResourceManager.GetString("Settings_LotteryImagePositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置输入到人脸检测模型的画面宽高（0 表示使用原始帧）.
        /// </summary>
        public static string Settings_ModelInputSizeDesc {
            get {
                return ResourceManager.GetString("Settings_ModelInputSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开 data/cv_models，用于添加 ONNX 模型文件.
        /// </summary>
        public static string Settings_OpenModelFolderDesc {
            get {
                return ResourceManager.GetString("Settings_OpenModelFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取动画圆形框颜色.
        /// </summary>
        public static string Settings_PickerFrameColorDesc {
            get {
                return ResourceManager.GetString("Settings_PickerFrameColorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取动画持续时间（秒）.
        /// </summary>
        public static string Settings_PickingDurationSecondsDesc {
            get {
                return ResourceManager.GetString("Settings_PickingDurationSecondsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取过程中是否播放音效.
        /// </summary>
        public static string Settings_PlayProcessAudioDesc {
            get {
                return ResourceManager.GetString("Settings_PlayProcessAudioDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取结果展示时是否播放音效.
        /// </summary>
        public static string Settings_PlayResultAudioDesc {
            get {
                return ResourceManager.GetString("Settings_PlayResultAudioDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置结果布局动画时长（毫秒）.
        /// </summary>
        public static string Settings_ResultFlowAnimationDurationDesc {
            get {
                return ResourceManager.GetString("Settings_ResultFlowAnimationDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置结果布局出现动画效果.
        /// </summary>
        public static string Settings_ResultFlowAnimationStyleDesc {
            get {
                return ResourceManager.GetString("Settings_ResultFlowAnimationStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置随机组员显示格式.
        /// </summary>
        public static string Settings_ShowRandomDesc {
            get {
                return ResourceManager.GetString("Settings_ShowRandomDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置是否在结果中显示标签.
        /// </summary>
        public static string Settings_ShowTagsDesc {
            get {
                return ResourceManager.GetString("Settings_ShowTagsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置是否显示学生图片.
        /// </summary>
        public static string Settings_StudentImageDesc {
            get {
                return ResourceManager.GetString("Settings_StudentImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理学生图片文件，文件名需与学生姓名一致.
        /// </summary>
        public static string Settings_StudentImageFolderDesc {
            get {
                return ResourceManager.GetString("Settings_StudentImageFolderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生头像在结果中的位置.
        /// </summary>
        public static string Settings_StudentImagePositionDesc {
            get {
                return ResourceManager.GetString("Settings_StudentImagePositionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否使用全局字体设置.
        /// </summary>
        public static string Settings_UseGlobalFontDesc {
            get {
                return ResourceManager.GetString("Settings_UseGlobalFontDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示随机组员格式.
        /// </summary>
        public static string ShowRandom {
            get {
                return ResourceManager.GetString("ShowRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组名[短横杠]姓名.
        /// </summary>
        public static string ShowRandomDash {
            get {
                return ResourceManager.GetString("ShowRandomDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不显示.
        /// </summary>
        public static string ShowRandomHide {
            get {
                return ResourceManager.GetString("ShowRandomHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组名[换行]姓名.
        /// </summary>
        public static string ShowRandomNewline {
            get {
                return ResourceManager.GetString("ShowRandomNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示标签.
        /// </summary>
        public static string ShowTags {
            get {
                return ResourceManager.GetString("ShowTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示学生图片.
        /// </summary>
        public static string StudentImage {
            get {
                return ResourceManager.GetString("StudentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生图片文件夹.
        /// </summary>
        public static string StudentImageFolder {
            get {
                return ResourceManager.GetString("StudentImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string StudentImageFolderButton {
            get {
                return ResourceManager.GetString("StudentImageFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像位置.
        /// </summary>
        public static string StudentImagePosition {
            get {
                return ResourceManager.GetString("StudentImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部.
        /// </summary>
        public static string StudentImagePositionBottom {
            get {
                return ResourceManager.GetString("StudentImagePositionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左部.
        /// </summary>
        public static string StudentImagePositionLeft {
            get {
                return ResourceManager.GetString("StudentImagePositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右部.
        /// </summary>
        public static string StudentImagePositionRight {
            get {
                return ResourceManager.GetString("StudentImagePositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部.
        /// </summary>
        public static string StudentImagePositionTop {
            get {
                return ResourceManager.GetString("StudentImagePositionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用全局字体.
        /// </summary>
        public static string UseGlobalFont {
            get {
                return ResourceManager.GetString("UseGlobalFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用自定义字体.
        /// </summary>
        public static string UseGlobalFontCustom {
            get {
                return ResourceManager.GetString("UseGlobalFontCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随全局字体.
        /// </summary>
        public static string UseGlobalFontFollow {
            get {
                return ResourceManager.GetString("UseGlobalFontFollow", resourceCulture);
            }
        }
    }
}
