//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.DrawSettingsPage {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.DrawSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string RollCallSettings {
            get {
                return ResourceManager.GetString("RollCallSettings", resourceCulture);
            }
        }

        public static string QuickDrawSettings {
            get {
                return ResourceManager.GetString("QuickDrawSettings", resourceCulture);
            }
        }

        public static string LotterySettings {
            get {
                return ResourceManager.GetString("LotterySettings", resourceCulture);
            }
        }
        
        public static string FaceDetectorSettings {
            get {
                return ResourceManager.GetString("FaceDetectorSettings", resourceCulture);
            }
        }
        
        public static string DrawSettingsNavHint {
            get {
                return ResourceManager.GetString("DrawSettingsNavHint", resourceCulture);
            }
        }

        public static string ListSpecificSettings {
            get {
                return ResourceManager.GetString("ListSpecificSettings", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectClass {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectClass", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectClassDesc {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectClassDesc", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectList {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectList", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectListDesc {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectListDesc", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectPool {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectPool", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSelectPoolDesc {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSelectPoolDesc", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSync {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSync", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSyncDesc {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSyncDesc", resourceCulture);
            }
        }

        public static string ListSpecificSettingsSyncButton {
            get {
                return ResourceManager.GetString("ListSpecificSettingsSyncButton", resourceCulture);
            }
        }

        public static string RollCallExtractionFunction {
            get {
                return ResourceManager.GetString("RollCallExtractionFunction", resourceCulture);
            }
        }

        public static string QuickDrawExtractionFunction {
            get {
                return ResourceManager.GetString("QuickDrawExtractionFunction", resourceCulture);
            }
        }

        public static string LotteryExtractionFunction {
            get {
                return ResourceManager.GetString("LotteryExtractionFunction", resourceCulture);
            }
        }
        
        public static string FaceDetectorExtractionFunction {
            get {
                return ResourceManager.GetString("FaceDetectorExtractionFunction", resourceCulture);
            }
        }
        
        public static string CameraSource {
            get {
                return ResourceManager.GetString("CameraSource", resourceCulture);
            }
        }
        
        public static string CameraSourceDesc {
            get {
                return ResourceManager.GetString("CameraSourceDesc", resourceCulture);
            }
        }

        public static string CameraDisplayResolution {
            get {
                return ResourceManager.GetString("CameraDisplayResolution", resourceCulture);
            }
        }

        public static string CameraDisplayResolutionDesc {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionDesc", resourceCulture);
            }
        }

        public static string CameraDisplayResolutionPlaceholder {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionPlaceholder", resourceCulture);
            }
        }

        public static string CameraDisplayResolutionAutoFormat {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionAutoFormat", resourceCulture);
            }
        }

        public static string CameraDisplayResolutionUnknown {
            get {
                return ResourceManager.GetString("CameraDisplayResolutionUnknown", resourceCulture);
            }
        }

        public static string CameraPreviewMode {
            get {
                return ResourceManager.GetString("CameraPreviewMode", resourceCulture);
            }
        }

        public static string CameraPreviewModeDesc {
            get {
                return ResourceManager.GetString("CameraPreviewModeDesc", resourceCulture);
            }
        }

        public static string CameraPreviewModePicking {
            get {
                return ResourceManager.GetString("CameraPreviewModePicking", resourceCulture);
            }
        }

        public static string CameraPreviewModeRecognition {
            get {
                return ResourceManager.GetString("CameraPreviewModeRecognition", resourceCulture);
            }
        }

        public static string FaceDetectorAdvancedSettings {
            get {
                return ResourceManager.GetString("FaceDetectorAdvancedSettings", resourceCulture);
            }
        }
        
        public static string DetectorType {
            get {
                return ResourceManager.GetString("DetectorType", resourceCulture);
            }
        }
        
        public static string DetectorTypeDesc {
            get {
                return ResourceManager.GetString("DetectorTypeDesc", resourceCulture);
            }
        }
        
        public static string DetectorTypePlaceholder {
            get {
                return ResourceManager.GetString("DetectorTypePlaceholder", resourceCulture);
            }
        }

        public static string OpenModelFolder {
            get {
                return ResourceManager.GetString("OpenModelFolder", resourceCulture);
            }
        }

        public static string OpenModelFolderDesc {
            get {
                return ResourceManager.GetString("OpenModelFolderDesc", resourceCulture);
            }
        }

        public static string OpenModelFolderButton {
            get {
                return ResourceManager.GetString("OpenModelFolderButton", resourceCulture);
            }
        }

        public static string ModelInputSize {
            get {
                return ResourceManager.GetString("ModelInputSize", resourceCulture);
            }
        }

        public static string ModelInputSizeDesc {
            get {
                return ResourceManager.GetString("ModelInputSizeDesc", resourceCulture);
            }
        }

        public static string FaceDetectorPickerAnimationSettings {
            get {
                return ResourceManager.GetString("FaceDetectorPickerAnimationSettings", resourceCulture);
            }
        }

        public static string PickerFrameColor {
            get {
                return ResourceManager.GetString("PickerFrameColor", resourceCulture);
            }
        }

        public static string PickerFrameColorDesc {
            get {
                return ResourceManager.GetString("PickerFrameColorDesc", resourceCulture);
            }
        }
        
        public static string PickingDurationSeconds {
            get {
                return ResourceManager.GetString("PickingDurationSeconds", resourceCulture);
            }
        }
        
        public static string PickingDurationSecondsDesc {
            get {
                return ResourceManager.GetString("PickingDurationSecondsDesc", resourceCulture);
            }
        }

        public static string PlayProcessAudio {
            get {
                return ResourceManager.GetString("PlayProcessAudio", resourceCulture);
            }
        }

        public static string PlayProcessAudioDesc {
            get {
                return ResourceManager.GetString("PlayProcessAudioDesc", resourceCulture);
            }
        }

        public static string PlayResultAudio {
            get {
                return ResourceManager.GetString("PlayResultAudio", resourceCulture);
            }
        }

        public static string PlayResultAudioDesc {
            get {
                return ResourceManager.GetString("PlayResultAudioDesc", resourceCulture);
            }
        }

        public static string DrawMode {
            get {
                return ResourceManager.GetString("DrawMode", resourceCulture);
            }
        }

        public static string DrawModeDesc {
            get {
                return ResourceManager.GetString("DrawModeDesc", resourceCulture);
            }
        }

        public static string DrawModeRepeat {
            get {
                return ResourceManager.GetString("DrawModeRepeat", resourceCulture);
            }
        }

        public static string DrawModeNoRepeat {
            get {
                return ResourceManager.GetString("DrawModeNoRepeat", resourceCulture);
            }
        }

        public static string DrawModeSemiRepeat {
            get {
                return ResourceManager.GetString("DrawModeSemiRepeat", resourceCulture);
            }
        }

        public static string ClearRecord {
            get {
                return ResourceManager.GetString("ClearRecord", resourceCulture);
            }
        }

        public static string ClearRecordDesc {
            get {
                return ResourceManager.GetString("ClearRecordDesc", resourceCulture);
            }
        }

        public static string ClearRecordRestart {
            get {
                return ResourceManager.GetString("ClearRecordRestart", resourceCulture);
            }
        }

        public static string ClearRecordAll {
            get {
                return ResourceManager.GetString("ClearRecordAll", resourceCulture);
            }
        }

        public static string HalfRepeat {
            get {
                return ResourceManager.GetString("HalfRepeat", resourceCulture);
            }
        }

        public static string HalfRepeatDesc {
            get {
                return ResourceManager.GetString("HalfRepeatDesc", resourceCulture);
            }
        }

        public static string DrawType {
            get {
                return ResourceManager.GetString("DrawType", resourceCulture);
            }
        }

        public static string DrawTypeDesc {
            get {
                return ResourceManager.GetString("DrawTypeDesc", resourceCulture);
            }
        }

        public static string DrawTypeRandom {
            get {
                return ResourceManager.GetString("DrawTypeRandom", resourceCulture);
            }
        }

        public static string DrawTypeFair {
            get {
                return ResourceManager.GetString("DrawTypeFair", resourceCulture);
            }
        }

        public static string DefaultClass {
            get {
                return ResourceManager.GetString("DefaultClass", resourceCulture);
            }
        }

        public static string DefaultClassDesc {
            get {
                return ResourceManager.GetString("DefaultClassDesc", resourceCulture);
            }
        }

        public static string DefaultClassPlaceholder {
            get {
                return ResourceManager.GetString("DefaultClassPlaceholder", resourceCulture);
            }
        }

        public static string DefaultPool {
            get {
                return ResourceManager.GetString("DefaultPool", resourceCulture);
            }
        }

        public static string DefaultPoolDesc {
            get {
                return ResourceManager.GetString("DefaultPoolDesc", resourceCulture);
            }
        }

        public static string DefaultPoolPlaceholder {
            get {
                return ResourceManager.GetString("DefaultPoolPlaceholder", resourceCulture);
            }
        }

        public static string DrawCount {
            get {
                return ResourceManager.GetString("DrawCount", resourceCulture);
            }
        }

        public static string DrawCountDesc {
            get {
                return ResourceManager.GetString("DrawCountDesc", resourceCulture);
            }
        }

        public static string DisableAfterClick {
            get {
                return ResourceManager.GetString("DisableAfterClick", resourceCulture);
            }
        }

        public static string DisableAfterClickDesc {
            get {
                return ResourceManager.GetString("DisableAfterClickDesc", resourceCulture);
            }
        }

        public static string RollCallDisplaySettings {
            get {
                return ResourceManager.GetString("RollCallDisplaySettings", resourceCulture);
            }
        }

        public static string QuickDrawDisplaySettings {
            get {
                return ResourceManager.GetString("QuickDrawDisplaySettings", resourceCulture);
            }
        }

        public static string LotteryDisplaySettings {
            get {
                return ResourceManager.GetString("LotteryDisplaySettings", resourceCulture);
            }
        }

        public static string UseGlobalFont {
            get {
                return ResourceManager.GetString("UseGlobalFont", resourceCulture);
            }
        }

        public static string UseGlobalFontDesc {
            get {
                return ResourceManager.GetString("UseGlobalFontDesc", resourceCulture);
            }
        }

        public static string UseGlobalFontFollow {
            get {
                return ResourceManager.GetString("UseGlobalFontFollow", resourceCulture);
            }
        }

        public static string UseGlobalFontCustom {
            get {
                return ResourceManager.GetString("UseGlobalFontCustom", resourceCulture);
            }
        }

        public static string CustomFont {
            get {
                return ResourceManager.GetString("CustomFont", resourceCulture);
            }
        }

        public static string CustomFontDesc {
            get {
                return ResourceManager.GetString("CustomFontDesc", resourceCulture);
            }
        }

        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }

        public static string FontSizeDesc {
            get {
                return ResourceManager.GetString("FontSizeDesc", resourceCulture);
            }
        }

        public static string DisplayFormat {
            get {
                return ResourceManager.GetString("DisplayFormat", resourceCulture);
            }
        }

        public static string DisplayFormatDesc {
            get {
                return ResourceManager.GetString("DisplayFormatDesc", resourceCulture);
            }
        }

        public static string DisplayFormatIdName {
            get {
                return ResourceManager.GetString("DisplayFormatIdName", resourceCulture);
            }
        }

        public static string DisplayFormatName {
            get {
                return ResourceManager.GetString("DisplayFormatName", resourceCulture);
            }
        }

        public static string DisplayFormatId {
            get {
                return ResourceManager.GetString("DisplayFormatId", resourceCulture);
            }
        }

        public static string DisplayStyle {
            get {
                return ResourceManager.GetString("DisplayStyle", resourceCulture);
            }
        }

        public static string DisplayStyleDesc {
            get {
                return ResourceManager.GetString("DisplayStyleDesc", resourceCulture);
            }
        }

        public static string DisplayStyleDefault {
            get {
                return ResourceManager.GetString("DisplayStyleDefault", resourceCulture);
            }
        }

        public static string DisplayStyleCard {
            get {
                return ResourceManager.GetString("DisplayStyleCard", resourceCulture);
            }
        }

        public static string ShowRandom {
            get {
                return ResourceManager.GetString("ShowRandom", resourceCulture);
            }
        }

        public static string ShowRandomDesc {
            get {
                return ResourceManager.GetString("ShowRandomDesc", resourceCulture);
            }
        }

        public static string ShowRandomHide {
            get {
                return ResourceManager.GetString("ShowRandomHide", resourceCulture);
            }
        }

        public static string ShowRandomNewline {
            get {
                return ResourceManager.GetString("ShowRandomNewline", resourceCulture);
            }
        }

        public static string ShowRandomDash {
            get {
                return ResourceManager.GetString("ShowRandomDash", resourceCulture);
            }
        }

        public static string ShowTags {
            get {
                return ResourceManager.GetString("ShowTags", resourceCulture);
            }
        }

        public static string ShowTagsDesc {
            get {
                return ResourceManager.GetString("ShowTagsDesc", resourceCulture);
            }
        }

        public static string RollCallAnimationSettings {
            get {
                return ResourceManager.GetString("RollCallAnimationSettings", resourceCulture);
            }
        }

        public static string QuickDrawAnimationSettings {
            get {
                return ResourceManager.GetString("QuickDrawAnimationSettings", resourceCulture);
            }
        }

        public static string LotteryAnimationSettings {
            get {
                return ResourceManager.GetString("LotteryAnimationSettings", resourceCulture);
            }
        }

        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }

        public static string AnimationDesc {
            get {
                return ResourceManager.GetString("AnimationDesc", resourceCulture);
            }
        }

        public static string AnimationManual {
            get {
                return ResourceManager.GetString("AnimationManual", resourceCulture);
            }
        }

        public static string AnimationAuto {
            get {
                return ResourceManager.GetString("AnimationAuto", resourceCulture);
            }
        }

        public static string AnimationDirect {
            get {
                return ResourceManager.GetString("AnimationDirect", resourceCulture);
            }
        }

        public static string AnimationInterval {
            get {
                return ResourceManager.GetString("AnimationInterval", resourceCulture);
            }
        }

        public static string AnimationIntervalDesc {
            get {
                return ResourceManager.GetString("AnimationIntervalDesc", resourceCulture);
            }
        }

        public static string AutoplayCount {
            get {
                return ResourceManager.GetString("AutoplayCount", resourceCulture);
            }
        }

        public static string AutoplayCountDesc {
            get {
                return ResourceManager.GetString("AutoplayCountDesc", resourceCulture);
            }
        }

        public static string ResultFlowAnimationStyle {
            get {
                return ResourceManager.GetString("ResultFlowAnimationStyle", resourceCulture);
            }
        }

        public static string ResultFlowAnimationStyleDesc {
            get {
                return ResourceManager.GetString("ResultFlowAnimationStyleDesc", resourceCulture);
            }
        }

        public static string ResultFlowAnimationDuration {
            get {
                return ResourceManager.GetString("ResultFlowAnimationDuration", resourceCulture);
            }
        }

        public static string ResultFlowAnimationDurationDesc {
            get {
                return ResourceManager.GetString("ResultFlowAnimationDurationDesc", resourceCulture);
            }
        }

        public static string RollCallColorThemeSettings {
            get {
                return ResourceManager.GetString("RollCallColorThemeSettings", resourceCulture);
            }
        }

        public static string QuickDrawColorThemeSettings {
            get {
                return ResourceManager.GetString("QuickDrawColorThemeSettings", resourceCulture);
            }
        }

        public static string LotteryColorThemeSettings {
            get {
                return ResourceManager.GetString("LotteryColorThemeSettings", resourceCulture);
            }
        }

        public static string AnimationColorTheme {
            get {
                return ResourceManager.GetString("AnimationColorTheme", resourceCulture);
            }
        }

        public static string AnimationColorThemeDesc {
            get {
                return ResourceManager.GetString("AnimationColorThemeDesc", resourceCulture);
            }
        }

        public static string AnimationColorThemeOff {
            get {
                return ResourceManager.GetString("AnimationColorThemeOff", resourceCulture);
            }
        }

        public static string AnimationColorThemeRandom {
            get {
                return ResourceManager.GetString("AnimationColorThemeRandom", resourceCulture);
            }
        }

        public static string AnimationColorThemeFixed {
            get {
                return ResourceManager.GetString("AnimationColorThemeFixed", resourceCulture);
            }
        }

        public static string AnimationFixedColor {
            get {
                return ResourceManager.GetString("AnimationFixedColor", resourceCulture);
            }
        }

        public static string AnimationFixedColorDesc {
            get {
                return ResourceManager.GetString("AnimationFixedColorDesc", resourceCulture);
            }
        }

        public static string LotteryImageSettings {
            get {
                return ResourceManager.GetString("LotteryImageSettings", resourceCulture);
            }
        }

        public static string LotteryImage {
            get {
                return ResourceManager.GetString("LotteryImage", resourceCulture);
            }
        }

        public static string LotteryImageDesc {
            get {
                return ResourceManager.GetString("LotteryImageDesc", resourceCulture);
            }
        }

        public static string LotteryImagePosition {
            get {
                return ResourceManager.GetString("LotteryImagePosition", resourceCulture);
            }
        }

        public static string LotteryImagePositionDesc {
            get {
                return ResourceManager.GetString("LotteryImagePositionDesc", resourceCulture);
            }
        }

        public static string LotteryImagePositionLeft {
            get {
                return ResourceManager.GetString("LotteryImagePositionLeft", resourceCulture);
            }
        }

        public static string LotteryImagePositionTop {
            get {
                return ResourceManager.GetString("LotteryImagePositionTop", resourceCulture);
            }
        }

        public static string LotteryImagePositionRight {
            get {
                return ResourceManager.GetString("LotteryImagePositionRight", resourceCulture);
            }
        }

        public static string LotteryImagePositionBottom {
            get {
                return ResourceManager.GetString("LotteryImagePositionBottom", resourceCulture);
            }
        }

        public static string LotteryImageFolder {
            get {
                return ResourceManager.GetString("LotteryImageFolder", resourceCulture);
            }
        }

        public static string LotteryImageFolderDesc {
            get {
                return ResourceManager.GetString("LotteryImageFolderDesc", resourceCulture);
            }
        }

        public static string LotteryImageFolderButton {
            get {
                return ResourceManager.GetString("LotteryImageFolderButton", resourceCulture);
            }
        }

        public static string RollCallStudentImageSettings {
            get {
                return ResourceManager.GetString("RollCallStudentImageSettings", resourceCulture);
            }
        }

        public static string StudentImage {
            get {
                return ResourceManager.GetString("StudentImage", resourceCulture);
            }
        }

        public static string StudentImageDesc {
            get {
                return ResourceManager.GetString("StudentImageDesc", resourceCulture);
            }
        }

        public static string StudentImagePosition {
            get {
                return ResourceManager.GetString("StudentImagePosition", resourceCulture);
            }
        }

        public static string StudentImagePositionDesc {
            get {
                return ResourceManager.GetString("StudentImagePositionDesc", resourceCulture);
            }
        }

        public static string StudentImagePositionLeft {
            get {
                return ResourceManager.GetString("StudentImagePositionLeft", resourceCulture);
            }
        }

        public static string StudentImagePositionTop {
            get {
                return ResourceManager.GetString("StudentImagePositionTop", resourceCulture);
            }
        }

        public static string StudentImagePositionRight {
            get {
                return ResourceManager.GetString("StudentImagePositionRight", resourceCulture);
            }
        }

        public static string StudentImagePositionBottom {
            get {
                return ResourceManager.GetString("StudentImagePositionBottom", resourceCulture);
            }
        }

        public static string StudentImageFolder {
            get {
                return ResourceManager.GetString("StudentImageFolder", resourceCulture);
            }
        }

        public static string StudentImageFolderDesc {
            get {
                return ResourceManager.GetString("StudentImageFolderDesc", resourceCulture);
            }
        }

        public static string StudentImageFolderButton {
            get {
                return ResourceManager.GetString("StudentImageFolderButton", resourceCulture);
            }
        }
    }
}
