//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementSubPages.ListSettingsSubPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(("SecRandom.Langs.SettingsPages.ListManagementSubPages.ListSettingsSubPage.Resource" +
                            "s"), typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 班级管理.
        /// </summary>
        public static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置数量.
        /// </summary>
        public static string CountSettings {
            get {
                return ResourceManager.GetString("CountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出奖品名单.
        /// </summary>
        public static string ExportPrizeList {
            get {
                return ResourceManager.GetString("ExportPrizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出学生名单.
        /// </summary>
        public static string ExportStudentList {
            get {
                return ResourceManager.GetString("ExportStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置性别.
        /// </summary>
        public static string GenderSettings {
            get {
                return ResourceManager.GetString("GenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置小组.
        /// </summary>
        public static string GroupSettings {
            get {
                return ResourceManager.GetString("GroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入奖品名单.
        /// </summary>
        public static string ImportPrizeList {
            get {
                return ResourceManager.GetString("ImportPrizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入学生名单.
        /// </summary>
        public static string ImportStudentList {
            get {
                return ResourceManager.GetString("ImportStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理抽奖用奖品名单，包括奖池管理、奖品导入导出等功能。.
        /// </summary>
        public static string LotteryListSettingsDesc {
            get {
                return ResourceManager.GetString("LotteryListSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖名单.
        /// </summary>
        public static string LotteryListSettingsTitle {
            get {
                return ResourceManager.GetString("LotteryListSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置姓名.
        /// </summary>
        public static string NameSettings {
            get {
                return ResourceManager.GetString("NameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池管理.
        /// </summary>
        public static string PoolManagement {
            get {
                return ResourceManager.GetString("PoolManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览表格.
        /// </summary>
        public static string PreviewTable {
            get {
                return ResourceManager.GetString("PreviewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品.
        /// </summary>
        public static string PrizeSettings {
            get {
                return ResourceManager.GetString("PrizeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理点名用学生名单，包括班级管理、学生导入导出等功能。.
        /// </summary>
        public static string RollCallListSettingsDesc {
            get {
                return ResourceManager.GetString("RollCallListSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名名单.
        /// </summary>
        public static string RollCallListSettingsTitle {
            get {
                return ResourceManager.GetString("RollCallListSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置班级名称.
        /// </summary>
        public static string SetClassName {
            get {
                return ResourceManager.GetString("SetClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖池名称.
        /// </summary>
        public static string SetPoolName {
            get {
                return ResourceManager.GetString("SetPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理点名用学生名单.
        /// </summary>
        public static string Settings_ClassManagementDesc {
            get {
                return ResourceManager.GetString("Settings_ClassManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品中奖数量.
        /// </summary>
        public static string Settings_CountSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_CountSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将奖品名单导出到文件.
        /// </summary>
        public static string Settings_ExportPrizeListDesc {
            get {
                return ResourceManager.GetString("Settings_ExportPrizeListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将学生名单导出到文件.
        /// </summary>
        public static string Settings_ExportStudentListDesc {
            get {
                return ResourceManager.GetString("Settings_ExportStudentListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生性别.
        /// </summary>
        public static string Settings_GenderSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GenderSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生所属小组.
        /// </summary>
        public static string Settings_GroupSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GroupSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入奖品名单.
        /// </summary>
        public static string Settings_ImportPrizeListDesc {
            get {
                return ResourceManager.GetString("Settings_ImportPrizeListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从文件导入学生名单.
        /// </summary>
        public static string Settings_ImportStudentListDesc {
            get {
                return ResourceManager.GetString("Settings_ImportStudentListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生姓名.
        /// </summary>
        public static string Settings_NameSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_NameSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理抽奖用奖品名单.
        /// </summary>
        public static string Settings_PoolManagementDesc {
            get {
                return ResourceManager.GetString("Settings_PoolManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品名称.
        /// </summary>
        public static string Settings_PrizeSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_PrizeSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置当前班级名称.
        /// </summary>
        public static string Settings_SetClassNameDesc {
            get {
                return ResourceManager.GetString("Settings_SetClassNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置当前奖池名称.
        /// </summary>
        public static string Settings_SetPoolNameDesc {
            get {
                return ResourceManager.GetString("Settings_SetPoolNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置学生标签.
        /// </summary>
        public static string Settings_TagSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_TagSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖品中奖权重.
        /// </summary>
        public static string Settings_WeightSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_WeightSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签设置.
        /// </summary>
        public static string TagSettings {
            get {
                return ResourceManager.GetString("TagSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置权重.
        /// </summary>
        public static string WeightSettings {
            get {
                return ResourceManager.GetString("WeightSettings", resourceCulture);
            }
        }
    }
}
