//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.BasicSettingsPage {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.BasicSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BasicFeatures {
            get {
                return ResourceManager.GetString("BasicFeatures", resourceCulture);
            }
        }

        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        public static string LanguageDesc {
            get {
                return ResourceManager.GetString("LanguageDesc", resourceCulture);
            }
        }

        public static string LanguageFollowSystem {
            get {
                return ResourceManager.GetString("LanguageFollowSystem", resourceCulture);
            }
        }

        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }

        public static string LanguageChineseSimplified {
            get {
                return ResourceManager.GetString("LanguageChineseSimplified", resourceCulture);
            }
        }
        
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        public static string AutoStartDesc {
            get {
                return ResourceManager.GetString("AutoStartDesc", resourceCulture);
            }
        }
        
        public static string ShowMainWindowOnStartup {
            get {
                return ResourceManager.GetString("ShowMainWindowOnStartup", resourceCulture);
            }
        }
        
        public static string ShowMainWindowOnStartupDesc {
            get {
                return ResourceManager.GetString("ShowMainWindowOnStartupDesc", resourceCulture);
            }
        }
        
        public static string AutoSaveWindowSize {
            get {
                return ResourceManager.GetString("AutoSaveWindowSize", resourceCulture);
            }
        }
        
        public static string AutoSaveWindowSizeDesc {
            get {
                return ResourceManager.GetString("AutoSaveWindowSizeDesc", resourceCulture);
            }
        }
        
        public static string MainWindowTopmost {
            get {
                return ResourceManager.GetString("MainWindowTopmost", resourceCulture);
            }
        }
        
        public static string MainWindowTopmostDesc {
            get {
                return ResourceManager.GetString("MainWindowTopmostDesc", resourceCulture);
            }
        }
        
        public static string MainWindowTopmostOff {
            get {
                return ResourceManager.GetString("MainWindowTopmostOff", resourceCulture);
            }
        }
        
        public static string MainWindowTopmostWindow {
            get {
                return ResourceManager.GetString("MainWindowTopmostWindow", resourceCulture);
            }
        }
        
        public static string MainWindowTopmostUia {
            get {
                return ResourceManager.GetString("MainWindowTopmostUia", resourceCulture);
            }
        }
        
        public static string BackgroundResident {
            get {
                return ResourceManager.GetString("BackgroundResident", resourceCulture);
            }
        }
        
        public static string BackgroundResidentDesc {
            get {
                return ResourceManager.GetString("BackgroundResidentDesc", resourceCulture);
            }
        }
        
        public static string RegisterUrlProtocolAndIpc {
            get {
                return ResourceManager.GetString("RegisterUrlProtocolAndIpc", resourceCulture);
            }
        }
        
        public static string RegisterUrlProtocolAndIpcDesc {
            get {
                return ResourceManager.GetString("RegisterUrlProtocolAndIpcDesc", resourceCulture);
            }
        }

        public static string Personalised {
            get {
                return ResourceManager.GetString("Personalised", resourceCulture);
            }
        }

        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        public static string ThemeDesc {
            get {
                return ResourceManager.GetString("ThemeDesc", resourceCulture);
            }
        }

        public static string ThemeFollowSystem {
            get {
                return ResourceManager.GetString("ThemeFollowSystem", resourceCulture);
            }
        }

        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        public static string OpenThemeManagement {
            get {
                return ResourceManager.GetString("OpenThemeManagement", resourceCulture);
            }
        }

        public static string OpenThemeManagementDesc {
            get {
                return ResourceManager.GetString("OpenThemeManagementDesc", resourceCulture);
            }
        }

        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }

        public static string FontDesc {
            get {
                return ResourceManager.GetString("FontDesc", resourceCulture);
            }
        }

        public static string FontWeight {
            get {
                return ResourceManager.GetString("FontWeight", resourceCulture);
            }
        }

        public static string FontWeightDesc {
            get {
                return ResourceManager.GetString("FontWeightDesc", resourceCulture);
            }
        }

        public static string FontWeightRegular {
            get {
                return ResourceManager.GetString("FontWeightRegular", resourceCulture);
            }
        }

        public static string FontWeightSemiBold {
            get {
                return ResourceManager.GetString("FontWeightSemiBold", resourceCulture);
            }
        }

        public static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }

        public static string DpiScale {
            get {
                return ResourceManager.GetString("DpiScale", resourceCulture);
            }
        }

        public static string DpiScaleDesc {
            get {
                return ResourceManager.GetString("DpiScaleDesc", resourceCulture);
            }
        }

        public static string DpiScaleAuto {
            get {
                return ResourceManager.GetString("DpiScaleAuto", resourceCulture);
            }
        }

        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }

        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }

        public static string LogViewerDesc {
            get {
                return ResourceManager.GetString("LogViewerDesc", resourceCulture);
            }
        }

        public static string LogViewerButton {
            get {
                return ResourceManager.GetString("LogViewerButton", resourceCulture);
            }
        }

        public static string BackupManager {
            get {
                return ResourceManager.GetString("BackupManager", resourceCulture);
            }
        }

        public static string BackupManagerDesc {
            get {
                return ResourceManager.GetString("BackupManagerDesc", resourceCulture);
            }
        }

        public static string BackupManagerButton {
            get {
                return ResourceManager.GetString("BackupManagerButton", resourceCulture);
            }
        }

        public static string ExportDiagnosticData {
            get {
                return ResourceManager.GetString("ExportDiagnosticData", resourceCulture);
            }
        }

        public static string ExportDiagnosticDataDesc {
            get {
                return ResourceManager.GetString("ExportDiagnosticDataDesc", resourceCulture);
            }
        }

        public static string ExportDiagnosticDataButton {
            get {
                return ResourceManager.GetString("ExportDiagnosticDataButton", resourceCulture);
            }
        }

        public static string ExportSettings {
            get {
                return ResourceManager.GetString("ExportSettings", resourceCulture);
            }
        }

        public static string ExportSettingsDesc {
            get {
                return ResourceManager.GetString("ExportSettingsDesc", resourceCulture);
            }
        }

        public static string ExportSettingsButton {
            get {
                return ResourceManager.GetString("ExportSettingsButton", resourceCulture);
            }
        }

        public static string ImportSettings {
            get {
                return ResourceManager.GetString("ImportSettings", resourceCulture);
            }
        }

        public static string ImportSettingsDesc {
            get {
                return ResourceManager.GetString("ImportSettingsDesc", resourceCulture);
            }
        }

        public static string ImportSettingsButton {
            get {
                return ResourceManager.GetString("ImportSettingsButton", resourceCulture);
            }
        }

        public static string ExportAllData {
            get {
                return ResourceManager.GetString("ExportAllData", resourceCulture);
            }
        }

        public static string ExportAllDataDesc {
            get {
                return ResourceManager.GetString("ExportAllDataDesc", resourceCulture);
            }
        }

        public static string ExportAllDataButton {
            get {
                return ResourceManager.GetString("ExportAllDataButton", resourceCulture);
            }
        }

        public static string ImportAllData {
            get {
                return ResourceManager.GetString("ImportAllData", resourceCulture);
            }
        }

        public static string ImportAllDataDesc {
            get {
                return ResourceManager.GetString("ImportAllDataDesc", resourceCulture);
            }
        }

        public static string ImportAllDataButton {
            get {
                return ResourceManager.GetString("ImportAllDataButton", resourceCulture);
            }
        }

        public static string FeatureInDevelopment {
            get {
                return ResourceManager.GetString("FeatureInDevelopment", resourceCulture);
            }
        }
    }
}
