//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.BasicSettingsPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.BasicSettingsPage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动保存窗口大小.
        /// </summary>
        public static string AutoSaveWindowSize {
            get {
                return ResourceManager.GetString("AutoSaveWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否自动保存窗口大小.
        /// </summary>
        public static string AutoSaveWindowSizeDesc {
            get {
                return ResourceManager.GetString("AutoSaveWindowSizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开机自启.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件是否随系统启动自动运行.
        /// </summary>
        public static string AutoStartDesc {
            get {
                return ResourceManager.GetString("AutoStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台驻留.
        /// </summary>
        public static string BackgroundResident {
            get {
                return ResourceManager.GetString("BackgroundResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭所有窗口后是否仍在后台常驻.
        /// </summary>
        public static string BackgroundResidentDesc {
            get {
                return ResourceManager.GetString("BackgroundResidentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份管理.
        /// </summary>
        public static string BackupManager {
            get {
                return ResourceManager.GetString("BackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份管理.
        /// </summary>
        public static string BackupManagerButton {
            get {
                return ResourceManager.GetString("BackupManagerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理自动备份与手动备份.
        /// </summary>
        public static string BackupManagerDesc {
            get {
                return ResourceManager.GetString("BackupManagerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础功能.
        /// </summary>
        public static string BasicFeatures {
            get {
                return ResourceManager.GetString("BasicFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据管理.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI缩放.
        /// </summary>
        public static string DpiScale {
            get {
                return ResourceManager.GetString("DpiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string DpiScaleAuto {
            get {
                return ResourceManager.GetString("DpiScaleAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整软件界面缩放比例（部分情况下需重启生效）.
        /// </summary>
        public static string DpiScaleDesc {
            get {
                return ResourceManager.GetString("DpiScaleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出所有数据.
        /// </summary>
        public static string ExportAllData {
            get {
                return ResourceManager.GetString("ExportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出所有数据.
        /// </summary>
        public static string ExportAllDataButton {
            get {
                return ResourceManager.GetString("ExportAllDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出全部数据和设置.
        /// </summary>
        public static string ExportAllDataDesc {
            get {
                return ResourceManager.GetString("ExportAllDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string ExportDiagnosticData {
            get {
                return ResourceManager.GetString("ExportDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string ExportDiagnosticDataButton {
            get {
                return ResourceManager.GetString("ExportDiagnosticDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出诊断信息，用于排查问题.
        /// </summary>
        public static string ExportDiagnosticDataDesc {
            get {
                return ResourceManager.GetString("ExportDiagnosticDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string ExportSettings {
            get {
                return ResourceManager.GetString("ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string ExportSettingsButton {
            get {
                return ResourceManager.GetString("ExportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前设置导出为配置文件，用于备份和迁移.
        /// </summary>
        public static string ExportSettingsDesc {
            get {
                return ResourceManager.GetString("ExportSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能正在开发中.
        /// </summary>
        public static string FeatureInDevelopment {
            get {
                return ResourceManager.GetString("FeatureInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择软件显示字体（部分控件需重启生效）.
        /// </summary>
        public static string FontDesc {
            get {
                return ResourceManager.GetString("FontDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体粗细.
        /// </summary>
        public static string FontWeight {
            get {
                return ResourceManager.GetString("FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粗体.
        /// </summary>
        public static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件显示字体粗细（部分控件需重启生效）.
        /// </summary>
        public static string FontWeightDesc {
            get {
                return ResourceManager.GetString("FontWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string FontWeightRegular {
            get {
                return ResourceManager.GetString("FontWeightRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半粗.
        /// </summary>
        public static string FontWeightSemiBold {
            get {
                return ResourceManager.GetString("FontWeightSemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入所有数据.
        /// </summary>
        public static string ImportAllData {
            get {
                return ResourceManager.GetString("ImportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入所有数据.
        /// </summary>
        public static string ImportAllDataButton {
            get {
                return ResourceManager.GetString("ImportAllDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从备份文件恢复全部数据.
        /// </summary>
        public static string ImportAllDataDesc {
            get {
                return ResourceManager.GetString("ImportAllDataDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string ImportSettings {
            get {
                return ResourceManager.GetString("ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string ImportSettingsButton {
            get {
                return ResourceManager.GetString("ImportSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从配置文件导入设置，覆盖当前配置信息.
        /// </summary>
        public static string ImportSettingsDesc {
            get {
                return ResourceManager.GetString("ImportSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string LanguageChineseSimplified {
            get {
                return ResourceManager.GetString("LanguageChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择软件显示语言.
        /// </summary>
        public static string LanguageDesc {
            get {
                return ResourceManager.GetString("LanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string LanguageFollowSystem {
            get {
                return ResourceManager.GetString("LanguageFollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看日志.
        /// </summary>
        public static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看日志.
        /// </summary>
        public static string LogViewerButton {
            get {
                return ResourceManager.GetString("LogViewerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看和管理程序日志文件.
        /// </summary>
        public static string LogViewerDesc {
            get {
                return ResourceManager.GetString("LogViewerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗口置顶.
        /// </summary>
        public static string MainWindowTopmost {
            get {
                return ResourceManager.GetString("MainWindowTopmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择主窗口置顶方式（UIA置顶需以管理员运行）.
        /// </summary>
        public static string MainWindowTopmostDesc {
            get {
                return ResourceManager.GetString("MainWindowTopmostDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭置顶.
        /// </summary>
        public static string MainWindowTopmostOff {
            get {
                return ResourceManager.GetString("MainWindowTopmostOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIA置顶.
        /// </summary>
        public static string MainWindowTopmostUia {
            get {
                return ResourceManager.GetString("MainWindowTopmostUia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口置顶.
        /// </summary>
        public static string MainWindowTopmostWindow {
            get {
                return ResourceManager.GetString("MainWindowTopmostWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string OpenThemeManagement {
            get {
                return ResourceManager.GetString("OpenThemeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主题管理页面.
        /// </summary>
        public static string OpenThemeManagementDesc {
            get {
                return ResourceManager.GetString("OpenThemeManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性化.
        /// </summary>
        public static string Personalised {
            get {
                return ResourceManager.GetString("Personalised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL协议注册&amp;IPC服务.
        /// </summary>
        public static string RegisterUrlProtocolAndIpc {
            get {
                return ResourceManager.GetString("RegisterUrlProtocolAndIpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义URL协议(secrandom://)，并启用IPC通信，支持链接启动与外部联动.
        /// </summary>
        public static string RegisterUrlProtocolAndIpcDesc {
            get {
                return ResourceManager.GetString("RegisterUrlProtocolAndIpcDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动显示主窗口.
        /// </summary>
        public static string ShowMainWindowOnStartup {
            get {
                return ResourceManager.GetString("ShowMainWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件启动时是否自动显示主窗口.
        /// </summary>
        public static string ShowMainWindowOnStartupDesc {
            get {
                return ResourceManager.GetString("ShowMainWindowOnStartupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题模式.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色模式.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择软件显示主题模式.
        /// </summary>
        public static string ThemeDesc {
            get {
                return ResourceManager.GetString("ThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string ThemeFollowSystem {
            get {
                return ResourceManager.GetString("ThemeFollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色模式.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
    }
}
