//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagementSubPages.LotterySubPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagementSubPages.LotterySubPages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加奖品.
        /// </summary>
        public static string AddPrize {
            get {
                return ResourceManager.GetString("AddPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加标签.
        /// </summary>
        public static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除现有数据（覆盖导入）.
        /// </summary>
        public static string ClearExistingData {
            get {
                return ResourceManager.GetString("ClearExistingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下 {0} 个奖池将被删除：
        ///{1}
        ///
        ///此操作不可撤销，是否继续？.
        /// </summary>
        public static string ConfirmDeleteDesc {
            get {
                return ResourceManager.GetString("ConfirmDeleteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除奖品 &apos;{0}&apos; 吗？.
        /// </summary>
        public static string ConfirmDeletePrize {
            get {
                return ResourceManager.GetString("ConfirmDeletePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量设置已保存.
        /// </summary>
        public static string CountSettingsSaved {
            get {
                return ResourceManager.GetString("CountSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量设置.
        /// </summary>
        public static string CountSettingsTitle {
            get {
                return ResourceManager.GetString("CountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功创建 {0} 个奖池.
        /// </summary>
        public static string CreatedSuccess {
            get {
                return ResourceManager.GetString("CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV 格式.
        /// </summary>
        public static string CsvFormat {
            get {
                return ResourceManager.GetString("CsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV - 名称,权重,数量,标签.
        /// </summary>
        public static string CsvFormatDesc {
            get {
                return ResourceManager.GetString("CsvFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了 {0} 个奖池.
        /// </summary>
        public static string DeletedInfo {
            get {
                return ResourceManager.GetString("DeletedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复名称.
        /// </summary>
        public static string DuplicateNames {
            get {
                return ResourceManager.GetString("DuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现 {0} 个重复的奖池名称：
        ///{1}
        ///
        ///是否自动重命名？.
        /// </summary>
        public static string DuplicateNamesDesc {
            get {
                return ResourceManager.GetString("DuplicateNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑名称.
        /// </summary>
        public static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑奖品.
        /// </summary>
        public static string EditPrize {
            get {
                return ResourceManager.GetString("EditPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入数量.
        /// </summary>
        public static string EnterCount {
            get {
                return ResourceManager.GetString("EnterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入分组名称.
        /// </summary>
        public static string EnterGroupName {
            get {
                return ResourceManager.GetString("EnterGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入新名称.
        /// </summary>
        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入奖品名称.
        /// </summary>
        public static string EnterPrizeName {
            get {
                return ResourceManager.GetString("EnterPrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入标签名称.
        /// </summary>
        public static string EnterTag {
            get {
                return ResourceManager.GetString("EnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入权重.
        /// </summary>
        public static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出失败.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出格式.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出奖品名单.
        /// </summary>
        public static string ExportPrizeTitle {
            get {
                return ResourceManager.GetString("ExportPrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品名单已导出到：{0}.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入失败，请检查文件格式是否正确.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入选项.
        /// </summary>
        public static string ImportOptions {
            get {
                return ResourceManager.GetString("ImportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入奖品名单.
        /// </summary>
        public static string ImportPrizeTitle {
            get {
                return ResourceManager.GetString("ImportPrizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功导入 {0} 个奖品.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下奖池名称包含非法字符：
        ///{0}.
        /// </summary>
        public static string InvalidPoolName {
            get {
                return ResourceManager.GetString("InvalidPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 格式.
        /// </summary>
        public static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON - 奖池格式文件.
        /// </summary>
        public static string JsonFormatDesc {
            get {
                return ResourceManager.GetString("JsonFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载奖池名称失败.
        /// </summary>
        public static string LoadPoolNamesFailed {
            get {
                return ResourceManager.GetString("LoadPoolNamesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称设置已保存.
        /// </summary>
        public static string NameSettingsSaved {
            get {
                return ResourceManager.GetString("NameSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称设置.
        /// </summary>
        public static string NameSettingsTitle {
            get {
                return ResourceManager.GetString("NameSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有需要保存的更改.
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择奖池.
        /// </summary>
        public static string PleaseSelectPool {
            get {
                return ResourceManager.GetString("PleaseSelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择要删除的奖品.
        /// </summary>
        public static string PleaseSelectPrizeToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectPrizeToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择有效的文件.
        /// </summary>
        public static string PleaseSelectValidFile {
            get {
                return ResourceManager.GetString("PleaseSelectValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池名称列表.
        /// </summary>
        public static string PoolNameList {
            get {
                return ResourceManager.GetString("PoolNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入奖池名称，每行一个
        ///例如：
        ///一等奖池
        ///二等奖池
        ///三等奖池.
        /// </summary>
        public static string PoolNameWatermark {
            get {
                return ResourceManager.GetString("PoolNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品列表.
        /// </summary>
        public static string PrizeList {
            get {
                return ResourceManager.GetString("PrizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品名称.
        /// </summary>
        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品设置已保存.
        /// </summary>
        public static string PrizeSettingsSaved {
            get {
                return ResourceManager.GetString("PrizeSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品设置.
        /// </summary>
        public static string PrizeSettingsTitle {
            get {
                return ResourceManager.GetString("PrizeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除标签.
        /// </summary>
        public static string RemoveTag {
            get {
                return ResourceManager.GetString("RemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存失败：{0}.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存位置.
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存奖池名称失败.
        /// </summary>
        public static string SavePoolNamesFailed {
            get {
                return ResourceManager.GetString("SavePoolNamesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择文件.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要导入的文件.
        /// </summary>
        public static string SelectFileToImport {
            get {
                return ResourceManager.GetString("SelectFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择奖池.
        /// </summary>
        public static string SelectPool {
            get {
                return ResourceManager.GetString("SelectPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择保存位置.
        /// </summary>
        public static string SelectSaveLocation {
            get {
                return ResourceManager.GetString("SelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置奖池名称.
        /// </summary>
        public static string SetPoolNameTitle {
            get {
                return ResourceManager.GetString("SetPoolNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品中奖数量。.
        /// </summary>
        public static string Settings_CountSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_CountSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品适用性别。.
        /// </summary>
        public static string Settings_GenderSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GenderSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别设置已保存.
        /// </summary>
        public static string Settings_GenderSettingsSaved {
            get {
                return ResourceManager.GetString("Settings_GenderSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别设置.
        /// </summary>
        public static string Settings_GenderSettingsTitle {
            get {
                return ResourceManager.GetString("Settings_GenderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品所属分组。.
        /// </summary>
        public static string Settings_GroupSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_GroupSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组设置已保存.
        /// </summary>
        public static string Settings_GroupSettingsSaved {
            get {
                return ResourceManager.GetString("Settings_GroupSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组设置.
        /// </summary>
        public static string Settings_GroupSettingsTitle {
            get {
                return ResourceManager.GetString("Settings_GroupSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品名称。选择奖品后可以修改其名称。.
        /// </summary>
        public static string Settings_NameSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_NameSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品名称。选择奖品后可以修改其名称。.
        /// </summary>
        public static string Settings_PrizeSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_PrizeSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此输入奖池名称，每行一个奖池名称。保存后将自动创建对应的奖池文件。.
        /// </summary>
        public static string Settings_SetPoolNameDesc {
            get {
                return ResourceManager.GetString("Settings_SetPoolNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品标签。选择奖品后可以添加或删除标签。.
        /// </summary>
        public static string Settings_TagSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_TagSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签设置已保存.
        /// </summary>
        public static string Settings_TagSettingsSaved {
            get {
                return ResourceManager.GetString("Settings_TagSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此设置奖品中奖权重。权重越高，中奖概率越大。.
        /// </summary>
        public static string Settings_WeightSettingsDesc {
            get {
                return ResourceManager.GetString("Settings_WeightSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始导出.
        /// </summary>
        public static string StartExport {
            get {
                return ResourceManager.GetString("StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始导入.
        /// </summary>
        public static string StartImport {
            get {
                return ResourceManager.GetString("StartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持的文件格式：.
        /// </summary>
        public static string SupportedFormats {
            get {
                return ResourceManager.GetString("SupportedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签设置.
        /// </summary>
        public static string TagSettingsTitle {
            get {
                return ResourceManager.GetString("TagSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT 格式（仅名称）.
        /// </summary>
        public static string TxtFormat {
            get {
                return ResourceManager.GetString("TxtFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT - 每行一个奖品名称.
        /// </summary>
        public static string TxtFormatDesc {
            get {
                return ResourceManager.GetString("TxtFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未保存的更改.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您有未保存的更改，是否放弃？.
        /// </summary>
        public static string UnsavedChangesDesc {
            get {
                return ResourceManager.GetString("UnsavedChangesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重设置已保存.
        /// </summary>
        public static string WeightSettingsSaved {
            get {
                return ResourceManager.GetString("WeightSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重设置.
        /// </summary>
        public static string WeightSettingsTitle {
            get {
                return ResourceManager.GetString("WeightSettingsTitle", resourceCulture);
            }
        }
    }
}
